export interface Pokemon {
  index: string;
  name: string;
  type1: string;
  type2: string;
}

export const pokemons: Pokemon[] = [
  { index: '#0001', name: 'Bulbasaur', type1: 'Grass', type2: 'Poison' },
  { index: '#0002', name: 'Ivysaur', type1: 'Grass', type2: 'Poison' },
  { index: '#0003', name: 'Venusaur', type1: 'Grass', type2: 'Poison' },
  { index: '#0004', name: 'Charmander', type1: 'Fire', type2: '' },
  { index: '#0005', name: 'Charmeleon', type1: 'Fire', type2: '' },
  { index: '#0006', name: 'Charizard', type1: 'Fire', type2: 'Flying' },
  { index: '#0007', name: 'Squirtle', type1: 'Water', type2: '' },
  { index: '#0008', name: 'Wartortle', type1: 'Water', type2: '' },
  { index: '#0009', name: 'Blastoise', type1: 'Water', type2: '' },
  { index: '#0010', name: 'Caterpie', type1: 'Bug', type2: '' },
  { index: '#0011', name: 'Metapod', type1: 'Bug', type2: '' },
  { index: '#0012', name: 'Butterfree', type1: 'Bug', type2: 'Flying' },
  { index: '#0013', name: 'Weedle', type1: 'Bug', type2: 'Poison' },
  { index: '#0014', name: 'Kakuna', type1: 'Bug', type2: 'Poison' },
  { index: '#0015', name: 'Beedrill', type1: 'Bug', type2: 'Poison' },
  { index: '#0016', name: 'Pidgey', type1: 'Normal', type2: 'Flying' },
  { index: '#0017', name: 'Pidgeotto', type1: 'Normal', type2: 'Flying' },
  { index: '#0018', name: 'Pidgeot', type1: 'Normal', type2: 'Flying' },
  { index: '#0019', name: 'Rattata', type1: 'Normal', type2: '' },
  { index: '#0019', name: 'Alolan Rattata', type1: 'Dark', type2: 'Normal' },
  { index: '#0020', name: 'Raticate', type1: 'Normal', type2: '' },
  { index: '#0020', name: 'Alolan Raticate', type1: 'Dark', type2: 'Normal' },
  { index: '#0021', name: 'Spearow', type1: 'Normal', type2: 'Flying' },
  { index: '#0022', name: 'Fearow', type1: 'Normal', type2: 'Flying' },
  { index: '#0023', name: 'Ekans', type1: 'Poison', type2: '' },
  { index: '#0024', name: 'Arbok', type1: 'Poison', type2: '' },
  { index: '#0025', name: 'Pikachu', type1: 'Electric', type2: '' },
  { index: '#0026', name: 'Raichu', type1: 'Electric', type2: '' },
  { index: '#0026', name: 'Alolan Raichu', type1: 'Electric', type2: 'Psychic' },
  { index: '#0027', name: 'Sandshrew', type1: 'Ground', type2: '' },
  { index: '#0027', name: 'Alolan Sandshrew', type1: 'Ice', type2: 'Steel' },
  { index: '#0028', name: 'Sandslash', type1: 'Ground', type2: '' },
  { index: '#0028', name: 'Alolan Sandslash', type1: 'Ice', type2: 'Steel' },
  { index: '#0029', name: 'Nidoran♀', type1: 'Poison', type2: '' },
  { index: '#0030', name: 'Nidorina', type1: 'Poison', type2: '' },
  { index: '#0031', name: 'Nidoqueen', type1: 'Poison', type2: 'Ground' },
  { index: '#0032', name: 'Nidoran♂', type1: 'Poison', type2: '' },
  { index: '#0033', name: 'Nidorino', type1: 'Poison', type2: '' },
  { index: '#0034', name: 'Nidoking', type1: 'Poison', type2: 'Ground' },
  { index: '#0035', name: 'Clefairy', type1: 'Fairy', type2: '' },
  { index: '#0036', name: 'Clefable', type1: 'Fairy', type2: '' },
  { index: '#0037', name: 'Vulpix', type1: 'Fire', type2: '' },
  { index: '#0037', name: 'Alolan Vulpix', type1: 'Ice', type2: '' },
  { index: '#0038', name: 'Ninetales', type1: 'Fire', type2: '' },
  { index: '#0038', name: 'Alolan Ninetales', type1: 'Ice', type2: 'Fairy' },
  { index: '#0039', name: 'Jigglypuff', type1: 'Normal', type2: 'Fairy' },
  { index: '#0040', name: 'Wigglytuff', type1: 'Normal', type2: 'Fairy' },
  { index: '#0041', name: 'Zubat', type1: 'Poison', type2: 'Flying' },
  { index: '#0042', name: 'Golbat', type1: 'Poison', type2: 'Flying' },
  { index: '#0043', name: 'Oddish', type1: 'Grass', type2: 'Poison' },
  { index: '#0044', name: 'Gloom', type1: 'Grass', type2: 'Poison' },
  { index: '#0045', name: 'Vileplume', type1: 'Grass', type2: 'Poison' },
  { index: '#0046', name: 'Paras', type1: 'Bug', type2: 'Grass' },
  { index: '#0047', name: 'Parasect', type1: 'Bug', type2: 'Grass' },
  { index: '#0048', name: 'Venonat', type1: 'Bug', type2: 'Poison' },
  { index: '#0049', name: 'Venomoth', type1: 'Bug', type2: 'Poison' },
  { index: '#0050', name: 'Diglett', type1: 'Ground', type2: '' },
  { index: '#0050', name: 'Alolan Diglett', type1: 'Ground', type2: 'Steel' },
  { index: '#0051', name: 'Dugtrio', type1: 'Ground', type2: '' },
  { index: '#0051', name: 'Alolan Dugtrio', type1: 'Ground', type2: 'Steel' },
  { index: '#0052', name: 'Meowth', type1: 'Normal', type2: '' },
  { index: '#0052', name: 'Alolan Meowth', type1: 'Dark', type2: '' },
  { index: '#0052', name: 'Galarian Meowth', type1: 'Steel', type2: '' },
  { index: '#0053', name: 'Persian', type1: 'Normal', type2: '' },
  { index: '#0053', name: 'Alolan Persian', type1: 'Dark', type2: '' },
  { index: '#0054', name: 'Psyduck', type1: 'Water', type2: '' },
  { index: '#0055', name: 'Golduck', type1: 'Water', type2: '' },
  { index: '#0056', name: 'Mankey', type1: 'Fighting', type2: '' },
  { index: '#0057', name: 'Primeape', type1: 'Fighting', type2: '' },
  { index: '#0058', name: 'Growlithe', type1: 'Fire', type2: '' },
  { index: '#0058', name: 'Hisuian Growlithe', type1: 'Fire', type2: 'Rock' },
  { index: '#0059', name: 'Arcanine', type1: 'Fire', type2: '' },
  { index: '#0059', name: 'Hisuian Arcanine', type1: 'Fire', type2: 'Rock' },
  { index: '#0060', name: 'Poliwag', type1: 'Water', type2: '' },
  { index: '#0061', name: 'Poliwhirl', type1: 'Water', type2: '' },
  { index: '#0062', name: 'Poliwrath', type1: 'Water', type2: 'Fighting' },
  { index: '#0063', name: 'Abra', type1: 'Psychic', type2: '' },
  { index: '#0064', name: 'Kadabra', type1: 'Psychic', type2: '' },
  { index: '#0065', name: 'Alakazam', type1: 'Psychic', type2: '' },
  { index: '#0066', name: 'Machop', type1: 'Fighting', type2: '' },
  { index: '#0067', name: 'Machoke', type1: 'Fighting', type2: '' },
  { index: '#0068', name: 'Machamp', type1: 'Fighting', type2: '' },
  { index: '#0069', name: 'Bellsprout', type1: 'Grass', type2: 'Poison' },
  { index: '#0070', name: 'Weepinbell', type1: 'Grass', type2: 'Poison' },
  { index: '#0071', name: 'Victreebel', type1: 'Grass', type2: 'Poison' },
  { index: '#0072', name: 'Tentacool', type1: 'Water', type2: 'Poison' },
  { index: '#0073', name: 'Tentacruel', type1: 'Water', type2: 'Poison' },
  { index: '#0074', name: 'Geodude', type1: 'Rock', type2: 'Ground' },
  { index: '#0074', name: 'Alolan Geodude', type1: 'Rock', type2: 'Electric' },
  { index: '#0075', name: 'Graveler', type1: 'Rock', type2: 'Ground' },
  { index: '#0075', name: 'Alolan Graveler', type1: 'Rock', type2: 'Electric' },
  { index: '#0076', name: 'Golem', type1: 'Rock', type2: 'Ground' },
  { index: '#0076', name: 'Alolan Golem', type1: 'Rock', type2: 'Electric' },
  { index: '#0077', name: 'Ponyta', type1: 'Fire', type2: '' },
  { index: '#0077', name: 'Galarian Ponyta', type1: 'Psychic', type2: '' },
  { index: '#0078', name: 'Rapidash', type1: 'Fire', type2: '' },
  { index: '#0078', name: 'Galarian Rapidash', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0079', name: 'Slowpoke', type1: 'Water', type2: 'Psychic' },
  { index: '#0079', name: 'Galarian Slowpoke', type1: 'Psychic', type2: '' },
  { index: '#0080', name: 'Slowbro', type1: 'Water', type2: 'Psychic' },
  { index: '#0080', name: 'Galarian Slowbro', type1: 'Poison', type2: 'Psychic' },
  { index: '#0081', name: 'Magnemite', type1: 'Electric', type2: 'Steel' },
  { index: '#0082', name: 'Magneton', type1: 'Electric', type2: 'Steel' },
  { index: '#0083', name: 'Farfetch\'d', type1: 'Normal', type2: 'Flying' },
  { index: '#0083', name: 'Farfetch\'Galarian d', type1: 'Fighting', type2: '' },
  { index: '#0084', name: 'Doduo', type1: 'Normal', type2: 'Flying' },
  { index: '#0085', name: 'Dodrio', type1: 'Normal', type2: 'Flying' },
  { index: '#0086', name: 'Seel', type1: 'Water', type2: '' },
  { index: '#0087', name: 'Dewgong', type1: 'Water', type2: 'Ice' },
  { index: '#0088', name: 'Grimer', type1: 'Poison', type2: '' },
  { index: '#0088', name: 'Alolan Grimer', type1: 'Poison', type2: 'Dark' },
  { index: '#0089', name: 'Muk', type1: 'Poison', type2: '' },
  { index: '#0089', name: 'Alolan Muk', type1: 'Poison', type2: 'Dark' },
  { index: '#0090', name: 'Shellder', type1: 'Water', type2: '' },
  { index: '#0091', name: 'Cloyster', type1: 'Water', type2: 'Ice' },
  { index: '#0092', name: 'Gastly', type1: 'Ghost', type2: 'Poison' },
  { index: '#0093', name: 'Haunter', type1: 'Ghost', type2: 'Poison' },
  { index: '#0094', name: 'Gengar', type1: 'Ghost', type2: 'Poison' },
  { index: '#0095', name: 'Onix', type1: 'Rock', type2: 'Ground' },
  { index: '#0096', name: 'Drowzee', type1: 'Psychic', type2: '' },
  { index: '#0097', name: 'Hypno', type1: 'Psychic', type2: '' },
  { index: '#0098', name: 'Krabby', type1: 'Water', type2: '' },
  { index: '#0099', name: 'Kingler', type1: 'Water', type2: '' },
  { index: '#0100', name: 'Voltorb', type1: 'Electric', type2: '' },
  { index: '#0100', name: 'Hisuian Voltorb', type1: 'Electric', type2: 'Grass' },
  { index: '#0101', name: 'Electrode', type1: 'Electric', type2: '' },
  { index: '#0101', name: 'Hisuian Electrode', type1: 'Electric', type2: 'Grass' },
  { index: '#0102', name: 'Exeggcute', type1: 'Grass', type2: 'Psychic' },
  { index: '#0103', name: 'Exeggutor', type1: 'Grass', type2: 'Psychic' },
  { index: '#0103', name: 'Alolan Exeggutor', type1: 'Grass', type2: 'Dragon' },
  { index: '#0104', name: 'Cubone', type1: 'Ground', type2: '' },
  { index: '#0105', name: 'Marowak', type1: 'Ground', type2: '' },
  { index: '#0105', name: 'Alolan Marowak', type1: 'Fire', type2: 'Ghost' },
  { index: '#0106', name: 'Hitmonlee', type1: 'Fighting', type2: '' },
  { index: '#0107', name: 'Hitmonchan', type1: 'Fighting', type2: '' },
  { index: '#0108', name: 'Lickitung', type1: 'Normal', type2: '' },
  { index: '#0109', name: 'Koffing', type1: 'Poison', type2: '' },
  { index: '#0110', name: 'Weezing', type1: 'Poison', type2: '' },
  { index: '#0110', name: 'Galarian Weezing', type1: 'Poison', type2: 'Fairy' },
  { index: '#0111', name: 'Rhyhorn', type1: 'Ground', type2: 'Rock' },
  { index: '#0112', name: 'Rhydon', type1: 'Ground', type2: 'Rock' },
  { index: '#0113', name: 'Chansey', type1: 'Normal', type2: '' },
  { index: '#0114', name: 'Tangela', type1: 'Grass', type2: '' },
  { index: '#0115', name: 'Kangaskhan', type1: 'Normal', type2: '' },
  { index: '#0116', name: 'Horsea', type1: 'Water', type2: '' },
  { index: '#0117', name: 'Seadra', type1: 'Water', type2: '' },
  { index: '#0118', name: 'Goldeen', type1: 'Water', type2: '' },
  { index: '#0119', name: 'Seaking', type1: 'Water', type2: '' },
  { index: '#0120', name: 'Staryu', type1: 'Water', type2: '' },
  { index: '#0121', name: 'Starmie', type1: 'Water', type2: 'Psychic' },
  { index: '#0122', name: 'Mr. Mime', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0122', name: 'Mr. Mime Galarian Form', type1: 'Ice', type2: 'Psychic' },
  { index: '#0123', name: 'Scyther', type1: 'Bug', type2: 'Flying' },
  { index: '#0124', name: 'Jynx', type1: 'Ice', type2: 'Psychic' },
  { index: '#0125', name: 'Electabuzz', type1: 'Electric', type2: '' },
  { index: '#0126', name: 'Magmar', type1: 'Fire', type2: '' },
  { index: '#0127', name: 'Pinsir', type1: 'Bug', type2: '' },
  { index: '#0128', name: 'Tauros', type1: 'Normal', type2: '' },
  { index: '#0128', name: 'Tauros Paldean Form (Combat Breed)', type1: 'Fighting', type2: '' },
  { index: '#0128', name: 'Tauros Paldean Form (Blaze Breed)', type1: 'Fighting', type2: 'Fire' },
  { index: '#0128', name: 'Tauros Paldean Form (Aqua Breed)', type1: 'Fighting', type2: 'Water' },
  { index: '#0129', name: 'Magikarp', type1: 'Water', type2: '' },
  { index: '#0130', name: 'Gyarados', type1: 'Water', type2: 'Flying' },
  { index: '#0131', name: 'Lapras', type1: 'Water', type2: 'Ice' },
  { index: '#0132', name: 'Ditto', type1: 'Normal', type2: '' },
  { index: '#0133', name: 'Eevee', type1: 'Normal', type2: '' },
  { index: '#0134', name: 'Vaporeon', type1: 'Water', type2: '' },
  { index: '#0135', name: 'Jolteon', type1: 'Electric', type2: '' },
  { index: '#0136', name: 'Flareon', type1: 'Fire', type2: '' },
  { index: '#0137', name: 'Porygon', type1: 'Normal', type2: '' },
  { index: '#0138', name: 'Omanyte', type1: 'Rock', type2: 'Water' },
  { index: '#0139', name: 'Omastar', type1: 'Rock', type2: 'Water' },
  { index: '#0140', name: 'Kabuto', type1: 'Rock', type2: 'Water' },
  { index: '#0141', name: 'Kabutops', type1: 'Rock', type2: 'Water' },
  { index: '#0142', name: 'Aerodactyl', type1: 'Rock', type2: 'Flying' },
  { index: '#0143', name: 'Snorlax', type1: 'Normal', type2: '' },
  { index: '#0144', name: 'Articuno', type1: 'Ice', type2: 'Flying' },
  { index: '#0144', name: 'Galarian Articuno', type1: 'Psychic', type2: 'Flying' },
  { index: '#0145', name: 'Zapdos', type1: 'Electric', type2: 'Flying' },
  { index: '#0145', name: 'Galarian Zapdos', type1: 'Fighting', type2: 'Flying' },
  { index: '#0146', name: 'Moltres', type1: 'Fire', type2: 'Flying' },
  { index: '#0146', name: 'Galarian Moltres', type1: 'Dark', type2: 'Flying' },
  { index: '#0147', name: 'Dratini', type1: 'Dragon', type2: '' },
  { index: '#0148', name: 'Dragonair', type1: 'Dragon', type2: '' },
  { index: '#0149', name: 'Dragonite', type1: 'Dragon', type2: 'Flying' },
  { index: '#0150', name: 'Mewtwo', type1: 'Psychic', type2: '' },
  { index: '#0151', name: 'Mew', type1: 'Psychic', type2: '' },
  { index: '#0152', name: 'Chikorita', type1: 'Grass', type2: '' },
  { index: '#0153', name: 'Bayleef', type1: 'Grass', type2: '' },
  { index: '#0154', name: 'Meganium', type1: 'Grass', type2: '' },
  { index: '#0155', name: 'Cyndaquil', type1: 'Fire', type2: '' },
  { index: '#0156', name: 'Quilava', type1: 'Fire', type2: '' },
  { index: '#0157', name: 'Typhlosion', type1: 'Fire', type2: '' },
  { index: '#0157', name: 'Hisuian Typhlosion', type1: 'Fire', type2: 'Ghost' },
  { index: '#0158', name: 'Totodile', type1: 'Water', type2: '' },
  { index: '#0159', name: 'Croconaw', type1: 'Water', type2: '' },
  { index: '#0160', name: 'Feraligatr', type1: 'Water', type2: '' },
  { index: '#0161', name: 'Sentret', type1: 'Normal', type2: '' },
  { index: '#0162', name: 'Furret', type1: 'Normal', type2: '' },
  { index: '#0163', name: 'Hoothoot', type1: 'Normal', type2: 'Flying' },
  { index: '#0164', name: 'Noctowl', type1: 'Normal', type2: 'Flying' },
  { index: '#0165', name: 'Ledyba', type1: 'Bug', type2: 'Flying' },
  { index: '#0166', name: 'Ledian', type1: 'Bug', type2: 'Flying' },
  { index: '#0167', name: 'Spinarak', type1: 'Bug', type2: 'Poison' },
  { index: '#0168', name: 'Ariados', type1: 'Bug', type2: 'Poison' },
  { index: '#0169', name: 'Crobat', type1: 'Poison', type2: 'Flying' },
  { index: '#0170', name: 'Chinchou', type1: 'Water', type2: 'Electric' },
  { index: '#0171', name: 'Lanturn', type1: 'Water', type2: 'Electric' },
  { index: '#0172', name: 'Pichu', type1: 'Electric', type2: '' },
  { index: '#0173', name: 'Cleffa', type1: 'Fairy', type2: '' },
  { index: '#0174', name: 'Igglybuff', type1: 'Normal', type2: 'Fairy' },
  { index: '#0175', name: 'Togepi', type1: 'Fairy', type2: '' },
  { index: '#0176', name: 'Togetic', type1: 'Fairy', type2: 'Flying' },
  { index: '#0177', name: 'Natu', type1: 'Psychic', type2: 'Flying' },
  { index: '#0178', name: 'Xatu', type1: 'Psychic', type2: 'Flying' },
  { index: '#0179', name: 'Mareep', type1: 'Electric', type2: '' },
  { index: '#0180', name: 'Flaaffy', type1: 'Electric', type2: '' },
  { index: '#0181', name: 'Ampharos', type1: 'Electric', type2: '' },
  { index: '#0182', name: 'Bellossom', type1: 'Grass', type2: '' },
  { index: '#0183', name: 'Marill', type1: 'Water', type2: 'Fairy' },
  { index: '#0184', name: 'Azumarill', type1: 'Water', type2: 'Fairy' },
  { index: '#0185', name: 'Sudowoodo', type1: 'Rock', type2: '' },
  { index: '#0186', name: 'Politoed', type1: 'Water', type2: '' },
  { index: '#0187', name: 'Hoppip', type1: 'Grass', type2: 'Flying' },
  { index: '#0188', name: 'Skiploom', type1: 'Grass', type2: 'Flying' },
  { index: '#0189', name: 'Jumpluff', type1: 'Grass', type2: 'Flying' },
  { index: '#0190', name: 'Aipom', type1: 'Normal', type2: '' },
  { index: '#0191', name: 'Sunkern', type1: 'Grass', type2: '' },
  { index: '#0192', name: 'Sunflora', type1: 'Grass', type2: '' },
  { index: '#0193', name: 'Yanma', type1: 'Bug', type2: 'Flying' },
  { index: '#0194', name: 'Wooper', type1: 'Water', type2: 'Ground' },
  { index: '#0194', name: 'Wooper Paldean Form', type1: 'Poison', type2: 'Ground' },
  { index: '#0195', name: 'Quagsire', type1: 'Water', type2: 'Ground' },
  { index: '#0196', name: 'Espeon', type1: 'Psychic', type2: '' },
  { index: '#0197', name: 'Umbreon', type1: 'Dark', type2: '' },
  { index: '#0198', name: 'Murkrow', type1: 'Dark', type2: 'Flying' },
  { index: '#0199', name: 'Slowking', type1: 'Water', type2: 'Psychic' },
  { index: '#0199', name: 'Galarian Slowking', type1: 'Poison', type2: 'Psychic' },
  { index: '#0200', name: 'Misdreavus', type1: 'Ghost', type2: '' },
  { index: '#0201', name: 'Unown One form', type1: 'Psychic', type2: '' },
  { index: '#0202', name: 'Wobbuffet', type1: 'Psychic', type2: '' },
  { index: '#0203', name: 'Girafarig', type1: 'Normal', type2: 'Psychic' },
  { index: '#0204', name: 'Pineco', type1: 'Bug', type2: '' },
  { index: '#0205', name: 'Forretress', type1: 'Bug', type2: 'Steel' },
  { index: '#0206', name: 'Dunsparce', type1: 'Normal', type2: '' },
  { index: '#0207', name: 'Gligar', type1: 'Ground', type2: 'Flying' },
  { index: '#0208', name: 'Steelix', type1: 'Steel', type2: 'Ground' },
  { index: '#0209', name: 'Snubbull', type1: 'Fairy', type2: '' },
  { index: '#0210', name: 'Granbull', type1: 'Fairy', type2: '' },
  { index: '#0211', name: 'Qwilfish', type1: 'Water', type2: 'Poison' },
  { index: '#0211', name: 'Hisuian Qwilfish', type1: 'Dark', type2: 'Poison' },
  { index: '#0212', name: 'Scizor', type1: 'Bug', type2: 'Steel' },
  { index: '#0213', name: 'Shuckle', type1: 'Bug', type2: 'Rock' },
  { index: '#0214', name: 'Heracross', type1: 'Bug', type2: 'Fighting' },
  { index: '#0215', name: 'Sneasel', type1: 'Dark', type2: 'Ice' },
  { index: '#0215', name: 'Hisuian Sneasel', type1: 'Fighting', type2: 'Poison' },
  { index: '#0216', name: 'Teddiursa', type1: 'Normal', type2: '' },
  { index: '#0217', name: 'Ursaring', type1: 'Normal', type2: '' },
  { index: '#0218', name: 'Slugma', type1: 'Fire', type2: '' },
  { index: '#0219', name: 'Magcargo', type1: 'Fire', type2: 'Rock' },
  { index: '#0220', name: 'Swinub', type1: 'Ice', type2: 'Ground' },
  { index: '#0221', name: 'Piloswine', type1: 'Ice', type2: 'Ground' },
  { index: '#0222', name: 'Corsola', type1: 'Water', type2: 'Rock' },
  { index: '#0222', name: 'Galarian Corsola', type1: 'Ghost', type2: '' },
  { index: '#0223', name: 'Remoraid', type1: 'Water', type2: '' },
  { index: '#0224', name: 'Octillery', type1: 'Water', type2: '' },
  { index: '#0225', name: 'Delibird', type1: 'Ice', type2: 'Flying' },
  { index: '#0226', name: 'Mantine', type1: 'Water', type2: 'Flying' },
  { index: '#0227', name: 'Skarmory', type1: 'Steel', type2: 'Flying' },
  { index: '#0228', name: 'Houndour', type1: 'Dark', type2: 'Fire' },
  { index: '#0229', name: 'Houndoom', type1: 'Dark', type2: 'Fire' },
  { index: '#0230', name: 'Kingdra', type1: 'Water', type2: 'Dragon' },
  { index: '#0231', name: 'Phanpy', type1: 'Ground', type2: '' },
  { index: '#0232', name: 'Donphan', type1: 'Ground', type2: '' },
  { index: '#0233', name: 'Porygon2', type1: 'Normal', type2: '' },
  { index: '#0234', name: 'Stantler', type1: 'Normal', type2: '' },
  { index: '#0235', name: 'Smeargle', type1: 'Normal', type2: '' },
  { index: '#0236', name: 'Tyrogue', type1: 'Fighting', type2: '' },
  { index: '#0237', name: 'Hitmontop', type1: 'Fighting', type2: '' },
  { index: '#0238', name: 'Smoochum', type1: 'Ice', type2: 'Psychic' },
  { index: '#0239', name: 'Elekid', type1: 'Electric', type2: '' },
  { index: '#0240', name: 'Magby', type1: 'Fire', type2: '' },
  { index: '#0241', name: 'Miltank', type1: 'Normal', type2: '' },
  { index: '#0242', name: 'Blissey', type1: 'Normal', type2: '' },
  { index: '#0243', name: 'Raikou', type1: 'Electric', type2: '' },
  { index: '#0244', name: 'Entei', type1: 'Fire', type2: '' },
  { index: '#0245', name: 'Suicune', type1: 'Water', type2: '' },
  { index: '#0246', name: 'Larvitar', type1: 'Rock', type2: 'Ground' },
  { index: '#0247', name: 'Pupitar', type1: 'Rock', type2: 'Ground' },
  { index: '#0248', name: 'Tyranitar', type1: 'Rock', type2: 'Dark' },
  { index: '#0249', name: 'Lugia', type1: 'Psychic', type2: 'Flying' },
  { index: '#0250', name: 'Ho-Oh', type1: 'Fire', type2: 'Flying' },
  { index: '#0251', name: 'Celebi', type1: 'Psychic', type2: 'Grass' },
  { index: '#0252', name: 'Treecko', type1: 'Grass', type2: '' },
  { index: '#0253', name: 'Grovyle', type1: 'Grass', type2: '' },
  { index: '#0254', name: 'Sceptile', type1: 'Grass', type2: '' },
  { index: '#0255', name: 'Torchic', type1: 'Fire', type2: '' },
  { index: '#0256', name: 'Combusken', type1: 'Fire', type2: 'Fighting' },
  { index: '#0257', name: 'Blaziken', type1: 'Fire', type2: 'Fighting' },
  { index: '#0258', name: 'Mudkip', type1: 'Water', type2: '' },
  { index: '#0259', name: 'Marshtomp', type1: 'Water', type2: 'Ground' },
  { index: '#0260', name: 'Swampert', type1: 'Water', type2: 'Ground' },
  { index: '#0261', name: 'Poochyena', type1: 'Dark', type2: '' },
  { index: '#0262', name: 'Mightyena', type1: 'Dark', type2: '' },
  { index: '#0263', name: 'Zigzagoon', type1: 'Normal', type2: '' },
  { index: '#0263', name: 'Galarian Zigzagoon', type1: 'Dark', type2: 'Normal' },
  { index: '#0264', name: 'Linoone', type1: 'Normal', type2: '' },
  { index: '#0264', name: 'Galarian Linoone', type1: 'Dark', type2: 'Normal' },
  { index: '#0265', name: 'Wurmple', type1: 'Bug', type2: '' },
  { index: '#0266', name: 'Silcoon', type1: 'Bug', type2: '' },
  { index: '#0267', name: 'Beautifly', type1: 'Bug', type2: 'Flying' },
  { index: '#0268', name: 'Cascoon', type1: 'Bug', type2: '' },
  { index: '#0269', name: 'Dustox', type1: 'Bug', type2: 'Poison' },
  { index: '#0270', name: 'Lotad', type1: 'Water', type2: 'Grass' },
  { index: '#0271', name: 'Lombre', type1: 'Water', type2: 'Grass' },
  { index: '#0272', name: 'Ludicolo', type1: 'Water', type2: 'Grass' },
  { index: '#0273', name: 'Seedot', type1: 'Grass', type2: '' },
  { index: '#0274', name: 'Nuzleaf', type1: 'Grass', type2: 'Dark' },
  { index: '#0275', name: 'Shiftry', type1: 'Grass', type2: 'Dark' },
  { index: '#0276', name: 'Taillow', type1: 'Normal', type2: 'Flying' },
  { index: '#0277', name: 'Swellow', type1: 'Normal', type2: 'Flying' },
  { index: '#0278', name: 'Wingull', type1: 'Water', type2: 'Flying' },
  { index: '#0279', name: 'Pelipper', type1: 'Water', type2: 'Flying' },
  { index: '#0280', name: 'Ralts', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0281', name: 'Kirlia', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0282', name: 'Gardevoir', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0283', name: 'Surskit', type1: 'Bug', type2: 'Water' },
  { index: '#0284', name: 'Masquerain', type1: 'Bug', type2: 'Flying' },
  { index: '#0285', name: 'Shroomish', type1: 'Grass', type2: '' },
  { index: '#0286', name: 'Breloom', type1: 'Grass', type2: 'Fighting' },
  { index: '#0287', name: 'Slakoth', type1: 'Normal', type2: '' },
  { index: '#0288', name: 'Vigoroth', type1: 'Normal', type2: '' },
  { index: '#0289', name: 'Slaking', type1: 'Normal', type2: '' },
  { index: '#0290', name: 'Nincada', type1: 'Bug', type2: 'Ground' },
  { index: '#0291', name: 'Ninjask', type1: 'Bug', type2: 'Flying' },
  { index: '#0292', name: 'Shedinja', type1: 'Bug', type2: 'Ghost' },
  { index: '#0293', name: 'Whismur', type1: 'Normal', type2: '' },
  { index: '#0294', name: 'Loudred', type1: 'Normal', type2: '' },
  { index: '#0295', name: 'Exploud', type1: 'Normal', type2: '' },
  { index: '#0296', name: 'Makuhita', type1: 'Fighting', type2: '' },
  { index: '#0297', name: 'Hariyama', type1: 'Fighting', type2: '' },
  { index: '#0298', name: 'Azurill', type1: 'Normal', type2: 'Fairy' },
  { index: '#0299', name: 'Nosepass', type1: 'Rock', type2: '' },
  { index: '#0300', name: 'Skitty', type1: 'Normal', type2: '' },
  { index: '#0301', name: 'Delcatty', type1: 'Normal', type2: '' },
  { index: '#0302', name: 'Sableye', type1: 'Dark', type2: 'Ghost' },
  { index: '#0303', name: 'Mawile', type1: 'Steel', type2: 'Fairy' },
  { index: '#0304', name: 'Aron', type1: 'Steel', type2: 'Rock' },
  { index: '#0305', name: 'Lairon', type1: 'Steel', type2: 'Rock' },
  { index: '#0306', name: 'Aggron', type1: 'Steel', type2: 'Rock' },
  { index: '#0307', name: 'Meditite', type1: 'Fighting', type2: 'Psychic' },
  { index: '#0308', name: 'Medicham', type1: 'Fighting', type2: 'Psychic' },
  { index: '#0309', name: 'Electrike', type1: 'Electric', type2: '' },
  { index: '#0310', name: 'Manectric', type1: 'Electric', type2: '' },
  { index: '#0311', name: 'Plusle', type1: 'Electric', type2: '' },
  { index: '#0312', name: 'Minun', type1: 'Electric', type2: '' },
  { index: '#0313', name: 'Volbeat', type1: 'Bug', type2: '' },
  { index: '#0314', name: 'Illumise', type1: 'Bug', type2: '' },
  { index: '#0315', name: 'Roselia', type1: 'Grass', type2: 'Poison' },
  { index: '#0316', name: 'Gulpin', type1: 'Poison', type2: '' },
  { index: '#0317', name: 'Swalot', type1: 'Poison', type2: '' },
  { index: '#0318', name: 'Carvanha', type1: 'Water', type2: 'Dark' },
  { index: '#0319', name: 'Sharpedo', type1: 'Water', type2: 'Dark' },
  { index: '#0320', name: 'Wailmer', type1: 'Water', type2: '' },
  { index: '#0321', name: 'Wailord', type1: 'Water', type2: '' },
  { index: '#0322', name: 'Numel', type1: 'Fire', type2: 'Ground' },
  { index: '#0323', name: 'Camerupt', type1: 'Fire', type2: 'Ground' },
  { index: '#0324', name: 'Torkoal', type1: 'Fire', type2: '' },
  { index: '#0325', name: 'Spoink', type1: 'Psychic', type2: '' },
  { index: '#0326', name: 'Grumpig', type1: 'Psychic', type2: '' },
  { index: '#0327', name: 'Spinda', type1: 'Normal', type2: '' },
  { index: '#0328', name: 'Trapinch', type1: 'Ground', type2: '' },
  { index: '#0329', name: 'Vibrava', type1: 'Ground', type2: 'Dragon' },
  { index: '#0330', name: 'Flygon', type1: 'Ground', type2: 'Dragon' },
  { index: '#0331', name: 'Cacnea', type1: 'Grass', type2: '' },
  { index: '#0332', name: 'Cacturne', type1: 'Grass', type2: 'Dark' },
  { index: '#0333', name: 'Swablu', type1: 'Normal', type2: 'Flying' },
  { index: '#0334', name: 'Altaria', type1: 'Dragon', type2: 'Flying' },
  { index: '#0335', name: 'Zangoose', type1: 'Normal', type2: '' },
  { index: '#0336', name: 'Seviper', type1: 'Poison', type2: '' },
  { index: '#0337', name: 'Lunatone', type1: 'Rock', type2: 'Psychic' },
  { index: '#0338', name: 'Solrock', type1: 'Rock', type2: 'Psychic' },
  { index: '#0339', name: 'Barboach', type1: 'Water', type2: 'Ground' },
  { index: '#0340', name: 'Whiscash', type1: 'Water', type2: 'Ground' },
  { index: '#0341', name: 'Corphish', type1: 'Water', type2: '' },
  { index: '#0342', name: 'Crawdaunt', type1: 'Water', type2: 'Dark' },
  { index: '#0343', name: 'Baltoy', type1: 'Ground', type2: 'Psychic' },
  { index: '#0344', name: 'Claydol', type1: 'Ground', type2: 'Psychic' },
  { index: '#0345', name: 'Lileep', type1: 'Rock', type2: 'Grass' },
  { index: '#0346', name: 'Cradily', type1: 'Rock', type2: 'Grass' },
  { index: '#0347', name: 'Anorith', type1: 'Rock', type2: 'Bug' },
  { index: '#0348', name: 'Armaldo', type1: 'Rock', type2: 'Bug' },
  { index: '#0349', name: 'Feebas', type1: 'Water', type2: '' },
  { index: '#0350', name: 'Milotic', type1: 'Water', type2: '' },
  { index: '#0351', name: 'Castform Normal', type1: 'Normal', type2: '' },
  { index: '#0351', name: 'Castform Sunny Form', type1: 'Fire', type2: '' },
  { index: '#0351', name: 'Castform Rainy Form', type1: 'Water', type2: '' },
  { index: '#0351', name: 'Castform Snowy Form', type1: 'Ice', type2: '' },
  { index: '#0352', name: 'Kecleon', type1: 'Normal', type2: '' },
  { index: '#0353', name: 'Shuppet', type1: 'Ghost', type2: '' },
  { index: '#0354', name: 'Banette', type1: 'Ghost', type2: '' },
  { index: '#0355', name: 'Duskull', type1: 'Ghost', type2: '' },
  { index: '#0356', name: 'Dusclops', type1: 'Ghost', type2: '' },
  { index: '#0357', name: 'Tropius', type1: 'Grass', type2: 'Flying' },
  { index: '#0358', name: 'Chimecho', type1: 'Psychic', type2: '' },
  { index: '#0359', name: 'Absol', type1: 'Dark', type2: '' },
  { index: '#0360', name: 'Wynaut', type1: 'Psychic', type2: '' },
  { index: '#0361', name: 'Snorunt', type1: 'Ice', type2: '' },
  { index: '#0362', name: 'Glalie', type1: 'Ice', type2: '' },
  { index: '#0363', name: 'Spheal', type1: 'Ice', type2: 'Water' },
  { index: '#0364', name: 'Sealeo', type1: 'Ice', type2: 'Water' },
  { index: '#0365', name: 'Walrein', type1: 'Ice', type2: 'Water' },
  { index: '#0366', name: 'Clamperl', type1: 'Water', type2: '' },
  { index: '#0367', name: 'Huntail', type1: 'Water', type2: '' },
  { index: '#0368', name: 'Gorebyss', type1: 'Water', type2: '' },
  { index: '#0369', name: 'Relicanth', type1: 'Water', type2: 'Rock' },
  { index: '#0370', name: 'Luvdisc', type1: 'Water', type2: '' },
  { index: '#0371', name: 'Bagon', type1: 'Dragon', type2: '' },
  { index: '#0372', name: 'Shelgon', type1: 'Dragon', type2: '' },
  { index: '#0373', name: 'Salamence', type1: 'Dragon', type2: 'Flying' },
  { index: '#0374', name: 'Beldum', type1: 'Steel', type2: 'Psychic' },
  { index: '#0375', name: 'Metang', type1: 'Steel', type2: 'Psychic' },
  { index: '#0376', name: 'Metagross', type1: 'Steel', type2: 'Psychic' },
  { index: '#0377', name: 'Regirock', type1: 'Rock', type2: '' },
  { index: '#0378', name: 'Regice', type1: 'Ice', type2: '' },
  { index: '#0379', name: 'Registeel', type1: 'Steel', type2: '' },
  { index: '#0380', name: 'Latias', type1: 'Dragon', type2: 'Psychic' },
  { index: '#0381', name: 'Latios', type1: 'Dragon', type2: 'Psychic' },
  { index: '#0382', name: 'Kyogre Kyogre', type1: 'Water', type2: '' },
  { index: '#0383', name: 'Groudon Groudon', type1: 'Ground', type2: '' },
  { index: '#0384', name: 'Rayquaza', type1: 'Dragon', type2: 'Flying' },
  { index: '#0385', name: 'Jirachi', type1: 'Steel', type2: 'Psychic' },
  { index: '#0386', name: 'Deoxys Normal Forme', type1: 'Psychic', type2: '' },
  { index: '#0386', name: 'Deoxys Attack Forme', type1: 'Psychic', type2: '' },
  { index: '#0386', name: 'Deoxys Defense Forme', type1: 'Psychic', type2: '' },
  { index: '#0386', name: 'Deoxys Speed Forme', type1: 'Psychic', type2: '' },
  { index: '#0387', name: 'Turtwig', type1: 'Grass', type2: '' },
  { index: '#0388', name: 'Grotle', type1: 'Grass', type2: '' },
  { index: '#0389', name: 'Torterra', type1: 'Grass', type2: 'Ground' },
  { index: '#0390', name: 'Chimchar', type1: 'Fire', type2: '' },
  { index: '#0391', name: 'Monferno', type1: 'Fire', type2: 'Fighting' },
  { index: '#0392', name: 'Infernape', type1: 'Fire', type2: 'Fighting' },
  { index: '#0393', name: 'Piplup', type1: 'Water', type2: '' },
  { index: '#0394', name: 'Prinplup', type1: 'Water', type2: '' },
  { index: '#0395', name: 'Empoleon', type1: 'Water', type2: 'Steel' },
  { index: '#0396', name: 'Starly', type1: 'Normal', type2: 'Flying' },
  { index: '#0397', name: 'Staravia', type1: 'Normal', type2: 'Flying' },
  { index: '#0398', name: 'Staraptor', type1: 'Normal', type2: 'Flying' },
  { index: '#0399', name: 'Bidoof', type1: 'Normal', type2: '' },
  { index: '#0400', name: 'Bibarel', type1: 'Normal', type2: 'Water' },
  { index: '#0401', name: 'Kricketot', type1: 'Bug', type2: '' },
  { index: '#0402', name: 'Kricketune', type1: 'Bug', type2: '' },
  { index: '#0403', name: 'Shinx', type1: 'Electric', type2: '' },
  { index: '#0404', name: 'Luxio', type1: 'Electric', type2: '' },
  { index: '#0405', name: 'Luxray', type1: 'Electric', type2: '' },
  { index: '#0406', name: 'Budew', type1: 'Grass', type2: 'Poison' },
  { index: '#0407', name: 'Roserade', type1: 'Grass', type2: 'Poison' },
  { index: '#0408', name: 'Cranidos', type1: 'Rock', type2: '' },
  { index: '#0409', name: 'Rampardos', type1: 'Rock', type2: '' },
  { index: '#0410', name: 'Shieldon', type1: 'Rock', type2: 'Steel' },
  { index: '#0411', name: 'Bastiodon', type1: 'Rock', type2: 'Steel' },
  { index: '#0412', name: 'Burmy Plant Cloak', type1: 'Bug', type2: '' },
  { index: '#0412', name: 'Burmy Sandy Cloak', type1: 'Bug', type2: '' },
  { index: '#0412', name: 'Burmy Trash Cloak', type1: 'Bug', type2: '' },
  { index: '#0413', name: 'Wormadam Plant Cloak', type1: 'Bug', type2: 'Grass' },
  { index: '#0413', name: 'Wormadam Sandy Cloak', type1: 'Bug', type2: 'Ground' },
  { index: '#0413', name: 'Wormadam Trash Cloak', type1: 'Bug', type2: 'Steel' },
  { index: '#0414', name: 'Mothim', type1: 'Bug', type2: 'Flying' },
  { index: '#0415', name: 'Combee', type1: 'Bug', type2: 'Flying' },
  { index: '#0416', name: 'Vespiquen', type1: 'Bug', type2: 'Flying' },
  { index: '#0417', name: 'Pachirisu', type1: 'Electric', type2: '' },
  { index: '#0418', name: 'Buizel', type1: 'Water', type2: '' },
  { index: '#0419', name: 'Floatzel', type1: 'Water', type2: '' },
  { index: '#0420', name: 'Cherubi', type1: 'Grass', type2: '' },
  { index: '#0421', name: 'Cherrim Overcast Form', type1: 'Grass', type2: '' },
  { index: '#0421', name: 'Cherrim Sunshine Form', type1: 'Grass', type2: '' },
  { index: '#0422', name: 'Shellos West Sea', type1: 'Water', type2: '' },
  { index: '#0422', name: 'Shellos East Sea', type1: 'Water', type2: '' },
  { index: '#0423', name: 'Gastrodon West Sea', type1: 'Water', type2: 'Ground' },
  { index: '#0423', name: 'Gastrodon East Sea', type1: 'Water', type2: 'Ground' },
  { index: '#0424', name: 'Ambipom', type1: 'Normal', type2: '' },
  { index: '#0425', name: 'Drifloon', type1: 'Ghost', type2: 'Flying' },
  { index: '#0426', name: 'Drifblim', type1: 'Ghost', type2: 'Flying' },
  { index: '#0427', name: 'Buneary', type1: 'Normal', type2: '' },
  { index: '#0428', name: 'Lopunny', type1: 'Normal', type2: '' },
  { index: '#0429', name: 'Mismagius', type1: 'Ghost', type2: '' },
  { index: '#0430', name: 'Honchkrow', type1: 'Dark', type2: 'Flying' },
  { index: '#0431', name: 'Glameow', type1: 'Normal', type2: '' },
  { index: '#0432', name: 'Purugly', type1: 'Normal', type2: '' },
  { index: '#0433', name: 'Chingling', type1: 'Psychic', type2: '' },
  { index: '#0434', name: 'Stunky', type1: 'Poison', type2: 'Dark' },
  { index: '#0435', name: 'Skuntank', type1: 'Poison', type2: 'Dark' },
  { index: '#0436', name: 'Bronzor', type1: 'Steel', type2: 'Psychic' },
  { index: '#0437', name: 'Bronzong', type1: 'Steel', type2: 'Psychic' },
  { index: '#0438', name: 'Bonsly', type1: 'Rock', type2: '' },
  { index: '#0439', name: 'Mime Jr.', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0440', name: 'Happiny', type1: 'Normal', type2: '' },
  { index: '#0441', name: 'Chatot', type1: 'Normal', type2: 'Flying' },
  { index: '#0442', name: 'Spiritomb', type1: 'Ghost', type2: 'Dark' },
  { index: '#0443', name: 'Gible', type1: 'Dragon', type2: 'Ground' },
  { index: '#0444', name: 'Gabite', type1: 'Dragon', type2: 'Ground' },
  { index: '#0445', name: 'Garchomp', type1: 'Dragon', type2: 'Ground' },
  { index: '#0446', name: 'Munchlax', type1: 'Normal', type2: '' },
  { index: '#0447', name: 'Riolu', type1: 'Fighting', type2: '' },
  { index: '#0448', name: 'Lucario', type1: 'Fighting', type2: 'Steel' },
  { index: '#0449', name: 'Hippopotas', type1: 'Ground', type2: '' },
  { index: '#0450', name: 'Hippowdon', type1: 'Ground', type2: '' },
  { index: '#0451', name: 'Skorupi', type1: 'Poison', type2: 'Bug' },
  { index: '#0452', name: 'Drapion', type1: 'Poison', type2: 'Dark' },
  { index: '#0453', name: 'Croagunk', type1: 'Poison', type2: 'Fighting' },
  { index: '#0454', name: 'Toxicroak', type1: 'Poison', type2: 'Fighting' },
  { index: '#0455', name: 'Carnivine', type1: 'Grass', type2: '' },
  { index: '#0456', name: 'Finneon', type1: 'Water', type2: '' },
  { index: '#0457', name: 'Lumineon', type1: 'Water', type2: '' },
  { index: '#0458', name: 'Mantyke', type1: 'Water', type2: 'Flying' },
  { index: '#0459', name: 'Snover', type1: 'Grass', type2: 'Ice' },
  { index: '#0460', name: 'Abomasnow', type1: 'Grass', type2: 'Ice' },
  { index: '#0461', name: 'Weavile', type1: 'Dark', type2: 'Ice' },
  { index: '#0462', name: 'Magnezone', type1: 'Electric', type2: 'Steel' },
  { index: '#0463', name: 'Lickilicky', type1: 'Normal', type2: '' },
  { index: '#0464', name: 'Rhyperior', type1: 'Ground', type2: 'Rock' },
  { index: '#0465', name: 'Tangrowth', type1: 'Grass', type2: '' },
  { index: '#0466', name: 'Electivire', type1: 'Electric', type2: '' },
  { index: '#0467', name: 'Magmortar', type1: 'Fire', type2: '' },
  { index: '#0468', name: 'Togekiss', type1: 'Fairy', type2: 'Flying' },
  { index: '#0469', name: 'Yanmega', type1: 'Bug', type2: 'Flying' },
  { index: '#0470', name: 'Leafeon', type1: 'Grass', type2: '' },
  { index: '#0471', name: 'Glaceon', type1: 'Ice', type2: '' },
  { index: '#0472', name: 'Gliscor', type1: 'Ground', type2: 'Flying' },
  { index: '#0473', name: 'Mamoswine', type1: 'Ice', type2: 'Ground' },
  { index: '#0474', name: 'Porygon-Z', type1: 'Normal', type2: '' },
  { index: '#0475', name: 'Gallade', type1: 'Psychic', type2: 'Fighting' },
  { index: '#0476', name: 'Probopass', type1: 'Rock', type2: 'Steel' },
  { index: '#0477', name: 'Dusknoir', type1: 'Ghost', type2: '' },
  { index: '#0478', name: 'Froslass', type1: 'Ice', type2: 'Ghost' },
  { index: '#0479', name: 'Rotom Rotom', type1: 'Electric', type2: 'Ghost' },
  { index: '#0479', name: 'Rotom Heat Rotom', type1: 'Electric', type2: 'Fire' },
  { index: '#0479', name: 'Rotom Wash Rotom', type1: 'Electric', type2: 'Water' },
  { index: '#0479', name: 'Rotom Frost Rotom', type1: 'Electric', type2: 'Ice' },
  { index: '#0479', name: 'Rotom Fan Rotom', type1: 'Electric', type2: 'Flying' },
  { index: '#0479', name: 'Rotom Mow Rotom', type1: 'Electric', type2: 'Grass' },
  { index: '#0480', name: 'Uxie', type1: 'Psychic', type2: '' },
  { index: '#0481', name: 'Mesprit', type1: 'Psychic', type2: '' },
  { index: '#0482', name: 'Azelf', type1: 'Psychic', type2: '' },
  { index: '#0483', name: 'Dialga', type1: 'Steel', type2: 'Dragon' },
  { index: '#0483', name: 'Dialga Origin Forme', type1: 'Steel', type2: 'Dragon' },
  { index: '#0484', name: 'Palkia', type1: 'Water', type2: 'Dragon' },
  { index: '#0484', name: 'Palkia Origin Forme', type1: 'Water', type2: 'Dragon' },
  { index: '#0485', name: 'Heatran', type1: 'Fire', type2: 'Steel' },
  { index: '#0486', name: 'Regigigas', type1: 'Normal', type2: '' },
  { index: '#0487', name: 'Giratina Altered Forme', type1: 'Ghost', type2: 'Dragon' },
  { index: '#0487', name: 'Giratina Origin Forme', type1: 'Ghost', type2: 'Dragon' },
  { index: '#0488', name: 'Cresselia', type1: 'Psychic', type2: '' },
  { index: '#0489', name: 'Phione', type1: 'Water', type2: '' },
  { index: '#0490', name: 'Manaphy', type1: 'Water', type2: '' },
  { index: '#0491', name: 'Darkrai', type1: 'Dark', type2: '' },
  { index: '#0492', name: 'Shaymin Land Forme', type1: 'Grass', type2: '' },
  { index: '#0492', name: 'Shaymin Sky Forme', type1: 'Grass', type2: 'Flying' },
  { index: '#0493', name: 'Arceus Arceus', type1: 'Normal', type2: '' },
  { index: '#0494', name: 'Victini', type1: 'Psychic', type2: 'Fire' },
  { index: '#0495', name: 'Snivy', type1: 'Grass', type2: '' },
  { index: '#0496', name: 'Servine', type1: 'Grass', type2: '' },
  { index: '#0497', name: 'Serperior', type1: 'Grass', type2: '' },
  { index: '#0498', name: 'Tepig', type1: 'Fire', type2: '' },
  { index: '#0499', name: 'Pignite', type1: 'Fire', type2: 'Fighting' },
  { index: '#0500', name: 'Emboar', type1: 'Fire', type2: 'Fighting' },
  { index: '#0501', name: 'Oshawott', type1: 'Water', type2: '' },
  { index: '#0502', name: 'Dewott', type1: 'Water', type2: '' },
  { index: '#0503', name: 'Samurott', type1: 'Water', type2: '' },
  { index: '#0503', name: 'Hisuian Samurott', type1: 'Water', type2: 'Dark' },
  { index: '#0504', name: 'Patrat', type1: 'Normal', type2: '' },
  { index: '#0505', name: 'Watchog', type1: 'Normal', type2: '' },
  { index: '#0506', name: 'Lillipup', type1: 'Normal', type2: '' },
  { index: '#0507', name: 'Herdier', type1: 'Normal', type2: '' },
  { index: '#0508', name: 'Stoutland', type1: 'Normal', type2: '' },
  { index: '#0509', name: 'Purrloin', type1: 'Dark', type2: '' },
  { index: '#0510', name: 'Liepard', type1: 'Dark', type2: '' },
  { index: '#0511', name: 'Pansage', type1: 'Grass', type2: '' },
  { index: '#0512', name: 'Simisage', type1: 'Grass', type2: '' },
  { index: '#0513', name: 'Pansear', type1: 'Fire', type2: '' },
  { index: '#0514', name: 'Simisear', type1: 'Fire', type2: '' },
  { index: '#0515', name: 'Panpour', type1: 'Water', type2: '' },
  { index: '#0516', name: 'Simipour', type1: 'Water', type2: '' },
  { index: '#0517', name: 'Munna', type1: 'Psychic', type2: '' },
  { index: '#0518', name: 'Musharna', type1: 'Psychic', type2: '' },
  { index: '#0519', name: 'Pidove', type1: 'Normal', type2: 'Flying' },
  { index: '#0520', name: 'Tranquill', type1: 'Normal', type2: 'Flying' },
  { index: '#0521', name: 'Unfezant', type1: 'Normal', type2: 'Flying' },
  { index: '#0522', name: 'Blitzle', type1: 'Electric', type2: '' },
  { index: '#0523', name: 'Zebstrika', type1: 'Electric', type2: '' },
  { index: '#0524', name: 'Roggenrola', type1: 'Rock', type2: '' },
  { index: '#0525', name: 'Boldore', type1: 'Rock', type2: '' },
  { index: '#0526', name: 'Gigalith', type1: 'Rock', type2: '' },
  { index: '#0527', name: 'Woobat', type1: 'Psychic', type2: 'Flying' },
  { index: '#0528', name: 'Swoobat', type1: 'Psychic', type2: 'Flying' },
  { index: '#0529', name: 'Drilbur', type1: 'Ground', type2: '' },
  { index: '#0530', name: 'Excadrill', type1: 'Ground', type2: 'Steel' },
  { index: '#0531', name: 'Audino', type1: 'Normal', type2: '' },
  { index: '#0532', name: 'Timburr', type1: 'Fighting', type2: '' },
  { index: '#0533', name: 'Gurdurr', type1: 'Fighting', type2: '' },
  { index: '#0534', name: 'Conkeldurr', type1: 'Fighting', type2: '' },
  { index: '#0535', name: 'Tympole', type1: 'Water', type2: '' },
  { index: '#0536', name: 'Palpitoad', type1: 'Water', type2: 'Ground' },
  { index: '#0537', name: 'Seismitoad', type1: 'Water', type2: 'Ground' },
  { index: '#0538', name: 'Throh', type1: 'Fighting', type2: '' },
  { index: '#0539', name: 'Sawk', type1: 'Fighting', type2: '' },
  { index: '#0540', name: 'Sewaddle', type1: 'Bug', type2: 'Grass' },
  { index: '#0541', name: 'Swadloon', type1: 'Bug', type2: 'Grass' },
  { index: '#0542', name: 'Leavanny', type1: 'Bug', type2: 'Grass' },
  { index: '#0543', name: 'Venipede', type1: 'Bug', type2: 'Poison' },
  { index: '#0544', name: 'Whirlipede', type1: 'Bug', type2: 'Poison' },
  { index: '#0545', name: 'Scolipede', type1: 'Bug', type2: 'Poison' },
  { index: '#0546', name: 'Cottonee', type1: 'Grass', type2: 'Fairy' },
  { index: '#0547', name: 'Whimsicott', type1: 'Grass', type2: 'Fairy' },
  { index: '#0548', name: 'Petilil', type1: 'Grass', type2: '' },
  { index: '#0549', name: 'Lilligant', type1: 'Grass', type2: '' },
  { index: '#0549', name: 'Hisuian Lilligant', type1: 'Grass', type2: 'Fighting' },
  { index: '#0550', name: 'Basculin Red-Striped Form', type1: 'Water', type2: '' },
  { index: '#0550', name: 'Basculin Blue-Striped Form', type1: 'Water', type2: '' },
  { index: '#0550', name: 'Basculin White-Striped Form', type1: 'Water', type2: '' },
  { index: '#0551', name: 'Sandile', type1: 'Ground', type2: 'Dark' },
  { index: '#0552', name: 'Krokorok', type1: 'Ground', type2: 'Dark' },
  { index: '#0553', name: 'Krookodile', type1: 'Ground', type2: 'Dark' },
  { index: '#0554', name: 'Darumaka', type1: 'Fire', type2: '' },
  { index: '#0554', name: 'Galarian Darumaka', type1: 'Ice', type2: '' },
  { index: '#0555', name: 'Darmanitan Standard Mode', type1: 'Fire', type2: '' },
  { index: '#0555', name: 'Darmanitan Zen Mode', type1: 'Fire', type2: 'Psychic' },
  { index: '#0555', name: 'Galarian Darmanitan', type1: 'Ice', type2: '' },
  { index: '#0555', name: 'Darmanitan Zen Mode (Galarian Form)', type1: 'Ice', type2: 'Fire' },
  { index: '#0556', name: 'Maractus', type1: 'Grass', type2: '' },
  { index: '#0557', name: 'Dwebble', type1: 'Bug', type2: 'Rock' },
  { index: '#0558', name: 'Crustle', type1: 'Bug', type2: 'Rock' },
  { index: '#0559', name: 'Scraggy', type1: 'Dark', type2: 'Fighting' },
  { index: '#0560', name: 'Scrafty', type1: 'Dark', type2: 'Fighting' },
  { index: '#0561', name: 'Sigilyph', type1: 'Psychic', type2: 'Flying' },
  { index: '#0562', name: 'Yamask', type1: 'Ghost', type2: '' },
  { index: '#0562', name: 'Galarian Yamask', type1: 'Ground', type2: 'Ghost' },
  { index: '#0563', name: 'Cofagrigus', type1: 'Ghost', type2: '' },
  { index: '#0564', name: 'Tirtouga', type1: 'Water', type2: 'Rock' },
  { index: '#0565', name: 'Carracosta', type1: 'Water', type2: 'Rock' },
  { index: '#0566', name: 'Archen', type1: 'Rock', type2: 'Flying' },
  { index: '#0567', name: 'Archeops', type1: 'Rock', type2: 'Flying' },
  { index: '#0568', name: 'Trubbish', type1: 'Poison', type2: '' },
  { index: '#0569', name: 'Garbodor', type1: 'Poison', type2: '' },
  { index: '#0570', name: 'Zorua', type1: 'Dark', type2: '' },
  { index: '#0570', name: 'Hisuian Zorua', type1: 'Normal', type2: 'Ghost' },
  { index: '#0571', name: 'Zoroark', type1: 'Dark', type2: '' },
  { index: '#0571', name: 'Hisuian Zoroark', type1: 'Normal', type2: 'Ghost' },
  { index: '#0572', name: 'Minccino', type1: 'Normal', type2: '' },
  { index: '#0573', name: 'Cinccino', type1: 'Normal', type2: '' },
  { index: '#0574', name: 'Gothita', type1: 'Psychic', type2: '' },
  { index: '#0575', name: 'Gothorita', type1: 'Psychic', type2: '' },
  { index: '#0576', name: 'Gothitelle', type1: 'Psychic', type2: '' },
  { index: '#0577', name: 'Solosis', type1: 'Psychic', type2: '' },
  { index: '#0578', name: 'Duosion', type1: 'Psychic', type2: '' },
  { index: '#0579', name: 'Reuniclus', type1: 'Psychic', type2: '' },
  { index: '#0580', name: 'Ducklett', type1: 'Water', type2: 'Flying' },
  { index: '#0581', name: 'Swanna', type1: 'Water', type2: 'Flying' },
  { index: '#0582', name: 'Vanillite', type1: 'Ice', type2: '' },
  { index: '#0583', name: 'Vanillish', type1: 'Ice', type2: '' },
  { index: '#0584', name: 'Vanilluxe', type1: 'Ice', type2: '' },
  { index: '#0585', name: 'Deerling Spring Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0585', name: 'Deerling Summer Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0585', name: 'Deerling Autumn Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0585', name: 'Deerling Winter Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0586', name: 'Sawsbuck Spring Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0586', name: 'Sawsbuck Summer Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0586', name: 'Sawsbuck Autumn Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0586', name: 'Sawsbuck Winter Form', type1: 'Normal', type2: 'Grass' },
  { index: '#0587', name: 'Emolga', type1: 'Electric', type2: 'Flying' },
  { index: '#0588', name: 'Karrablast', type1: 'Bug', type2: '' },
  { index: '#0589', name: 'Escavalier', type1: 'Bug', type2: 'Steel' },
  { index: '#0590', name: 'Foongus', type1: 'Grass', type2: 'Poison' },
  { index: '#0591', name: 'Amoonguss', type1: 'Grass', type2: 'Poison' },
  { index: '#0592', name: 'Frillish', type1: 'Water', type2: 'Ghost' },
  { index: '#0593', name: 'Jellicent', type1: 'Water', type2: 'Ghost' },
  { index: '#0594', name: 'Alomomola', type1: 'Water', type2: '' },
  { index: '#0595', name: 'Joltik', type1: 'Bug', type2: 'Electric' },
  { index: '#0596', name: 'Galvantula', type1: 'Bug', type2: 'Electric' },
  { index: '#0597', name: 'Ferroseed', type1: 'Grass', type2: 'Steel' },
  { index: '#0598', name: 'Ferrothorn', type1: 'Grass', type2: 'Steel' },
  { index: '#0599', name: 'Klink', type1: 'Steel', type2: '' },
  { index: '#0600', name: 'Klang', type1: 'Steel', type2: '' },
  { index: '#0601', name: 'Klinklang', type1: 'Steel', type2: '' },
  { index: '#0602', name: 'Tynamo', type1: 'Electric', type2: '' },
  { index: '#0603', name: 'Eelektrik', type1: 'Electric', type2: '' },
  { index: '#0604', name: 'Eelektross', type1: 'Electric', type2: '' },
  { index: '#0605', name: 'Elgyem', type1: 'Psychic', type2: '' },
  { index: '#0606', name: 'Beheeyem', type1: 'Psychic', type2: '' },
  { index: '#0607', name: 'Litwick', type1: 'Ghost', type2: 'Fire' },
  { index: '#0608', name: 'Lampent', type1: 'Ghost', type2: 'Fire' },
  { index: '#0609', name: 'Chandelure', type1: 'Ghost', type2: 'Fire' },
  { index: '#0610', name: 'Axew', type1: 'Dragon', type2: '' },
  { index: '#0611', name: 'Fraxure', type1: 'Dragon', type2: '' },
  { index: '#0612', name: 'Haxorus', type1: 'Dragon', type2: '' },
  { index: '#0613', name: 'Cubchoo', type1: 'Ice', type2: '' },
  { index: '#0614', name: 'Beartic', type1: 'Ice', type2: '' },
  { index: '#0615', name: 'Cryogonal', type1: 'Ice', type2: '' },
  { index: '#0616', name: 'Shelmet', type1: 'Bug', type2: '' },
  { index: '#0617', name: 'Accelgor', type1: 'Bug', type2: '' },
  { index: '#0618', name: 'Stunfisk', type1: 'Ground', type2: 'Electric' },
  { index: '#0618', name: 'Galarian Stunfisk', type1: 'Ground', type2: 'Steel' },
  { index: '#0619', name: 'Mienfoo', type1: 'Fighting', type2: '' },
  { index: '#0620', name: 'Mienshao', type1: 'Fighting', type2: '' },
  { index: '#0621', name: 'Druddigon', type1: 'Dragon', type2: '' },
  { index: '#0622', name: 'Golett', type1: 'Ground', type2: 'Ghost' },
  { index: '#0623', name: 'Golurk', type1: 'Ground', type2: 'Ghost' },
  { index: '#0624', name: 'Pawniard', type1: 'Dark', type2: 'Steel' },
  { index: '#0625', name: 'Bisharp', type1: 'Dark', type2: 'Steel' },
  { index: '#0626', name: 'Bouffalant', type1: 'Normal', type2: '' },
  { index: '#0627', name: 'Rufflet', type1: 'Normal', type2: 'Flying' },
  { index: '#0628', name: 'Braviary', type1: 'Normal', type2: 'Flying' },
  { index: '#0628', name: 'Hisuian Braviary', type1: 'Psychic', type2: 'Flying' },
  { index: '#0629', name: 'Vullaby', type1: 'Dark', type2: 'Flying' },
  { index: '#0630', name: 'Mandibuzz', type1: 'Dark', type2: 'Flying' },
  { index: '#0631', name: 'Heatmor', type1: 'Fire', type2: '' },
  { index: '#0632', name: 'Durant', type1: 'Bug', type2: 'Steel' },
  { index: '#0633', name: 'Deino', type1: 'Dark', type2: 'Dragon' },
  { index: '#0634', name: 'Zweilous', type1: 'Dark', type2: 'Dragon' },
  { index: '#0635', name: 'Hydreigon', type1: 'Dark', type2: 'Dragon' },
  { index: '#0636', name: 'Larvesta', type1: 'Bug', type2: 'Fire' },
  { index: '#0637', name: 'Volcarona', type1: 'Bug', type2: 'Fire' },
  { index: '#0638', name: 'Cobalion', type1: 'Steel', type2: 'Fighting' },
  { index: '#0639', name: 'Terrakion', type1: 'Rock', type2: 'Fighting' },
  { index: '#0640', name: 'Virizion', type1: 'Grass', type2: 'Fighting' },
  { index: '#0641', name: 'Tornadus Incarnate Forme', type1: 'Flying', type2: '' },
  { index: '#0641', name: 'Tornadus Therian Forme', type1: 'Flying', type2: '' },
  { index: '#0642', name: 'Thundurus Incarnate Forme', type1: 'Electric', type2: 'Flying' },
  { index: '#0642', name: 'Thundurus Therian Forme', type1: 'Electric', type2: 'Flying' },
  { index: '#0643', name: 'Reshiram', type1: 'Dragon', type2: 'Fire' },
  { index: '#0644', name: 'Zekrom', type1: 'Dragon', type2: 'Electric' },
  { index: '#0645', name: 'Landorus Incarnate Forme', type1: 'Ground', type2: 'Flying' },
  { index: '#0645', name: 'Landorus Therian Forme', type1: 'Ground', type2: 'Flying' },
  { index: '#0646', name: 'Kyurem Kyurem', type1: 'Dragon', type2: 'Ice' },
  { index: '#0646', name: 'Kyurem White Kyurem', type1: 'Dragon', type2: 'Ice' },
  { index: '#0646', name: 'Kyurem Black Kyurem', type1: 'Dragon', type2: 'Ice' },
  { index: '#0647', name: 'Keldeo Ordinary Form', type1: 'Water', type2: 'Fighting' },
  { index: '#0647', name: 'Keldeo Resolute Form', type1: 'Water', type2: 'Fighting' },
  { index: '#0648', name: 'Meloetta Aria Forme', type1: 'Normal', type2: 'Psychic' },
  { index: '#0648', name: 'Meloetta Pirouette Forme', type1: 'Normal', type2: 'Fighting' },
  { index: '#0649', name: 'Genesect Genesect (no drive)', type1: 'Bug', type2: 'Steel' },
  { index: '#0649', name: 'Genesect Genesect (Douse Drive)', type1: 'Bug', type2: 'Steel' },
  { index: '#0649', name: 'Genesect Genesect (Shock Drive)', type1: 'Bug', type2: 'Steel' },
  { index: '#0649', name: 'Genesect Genesect (Burn Drive)', type1: 'Bug', type2: 'Steel' },
  { index: '#0649', name: 'Genesect Genesect (Chill Drive)', type1: 'Bug', type2: 'Steel' },
  { index: '#0650', name: 'Chespin', type1: 'Grass', type2: '' },
  { index: '#0651', name: 'Quilladin', type1: 'Grass', type2: '' },
  { index: '#0652', name: 'Chesnaught', type1: 'Grass', type2: 'Fighting' },
  { index: '#0653', name: 'Fennekin', type1: 'Fire', type2: '' },
  { index: '#0654', name: 'Braixen', type1: 'Fire', type2: '' },
  { index: '#0655', name: 'Delphox', type1: 'Fire', type2: 'Psychic' },
  { index: '#0656', name: 'Froakie', type1: 'Water', type2: '' },
  { index: '#0657', name: 'Frogadier', type1: 'Water', type2: '' },
  { index: '#0658', name: 'Greninja', type1: 'Water', type2: 'Dark' },
  { index: '#0659', name: 'Bunnelby', type1: 'Normal', type2: '' },
  { index: '#0660', name: 'Diggersby', type1: 'Normal', type2: 'Ground' },
  { index: '#0661', name: 'Fletchling', type1: 'Normal', type2: 'Flying' },
  { index: '#0662', name: 'Fletchinder', type1: 'Fire', type2: 'Flying' },
  { index: '#0663', name: 'Talonflame', type1: 'Fire', type2: 'Flying' },
  { index: '#0664', name: 'Scatterbug', type1: 'Bug', type2: '' },
  { index: '#0665', name: 'Spewpa', type1: 'Bug', type2: '' },
  { index: '#0666', name: 'Vivillon Meadow Pattern', type1: 'Bug', type2: 'Flying' },
  { index: '#0667', name: 'Litleo', type1: 'Fire', type2: 'Normal' },
  { index: '#0668', name: 'Pyroar', type1: 'Fire', type2: 'Normal' },
  { index: '#0669', name: 'Flabébé Red Flower', type1: 'Fairy', type2: '' },
  { index: '#0669', name: 'Flabébé Yellow Flower', type1: 'Fairy', type2: '' },
  { index: '#0669', name: 'Flabébé Orange Flower', type1: 'Fairy', type2: '' },
  { index: '#0669', name: 'Flabébé Blue Flower', type1: 'Fairy', type2: '' },
  { index: '#0669', name: 'Flabébé White Flower', type1: 'Fairy', type2: '' },
  { index: '#0670', name: 'Floette Red Flower', type1: 'Fairy', type2: '' },
  { index: '#0670', name: 'Floette Yellow Flower', type1: 'Fairy', type2: '' },
  { index: '#0670', name: 'Floette Orange Flower', type1: 'Fairy', type2: '' },
  { index: '#0670', name: 'Floette Blue Flower', type1: 'Fairy', type2: '' },
  { index: '#0670', name: 'Floette White Flower', type1: 'Fairy', type2: '' },
  { index: '#0671', name: 'Florges Red Flower', type1: 'Fairy', type2: '' },
  { index: '#0671', name: 'Florges Yellow Flower', type1: 'Fairy', type2: '' },
  { index: '#0671', name: 'Florges Orange Flower', type1: 'Fairy', type2: '' },
  { index: '#0671', name: 'Florges Blue Flower', type1: 'Fairy', type2: '' },
  { index: '#0671', name: 'Florges White Flower', type1: 'Fairy', type2: '' },
  { index: '#0672', name: 'Skiddo', type1: 'Grass', type2: '' },
  { index: '#0673', name: 'Gogoat', type1: 'Grass', type2: '' },
  { index: '#0674', name: 'Pancham', type1: 'Fighting', type2: '' },
  { index: '#0675', name: 'Pangoro', type1: 'Fighting', type2: 'Dark' },
  { index: '#0676', name: 'Furfrou Natural Form', type1: 'Normal', type2: '' },
  { index: '#0677', name: 'Espurr', type1: 'Psychic', type2: '' },
  { index: '#0678', name: 'Meowstic Male', type1: 'Psychic', type2: '' },
  { index: '#0678', name: 'Meowstic Female', type1: 'Psychic', type2: '' },
  { index: '#0679', name: 'Honedge', type1: 'Steel', type2: 'Ghost' },
  { index: '#0680', name: 'Doublade', type1: 'Steel', type2: 'Ghost' },
  { index: '#0681', name: 'Aegislash Shield Forme', type1: 'Steel', type2: 'Ghost' },
  { index: '#0681', name: 'Aegislash Blade Forme', type1: 'Steel', type2: 'Ghost' },
  { index: '#0682', name: 'Spritzee', type1: 'Fairy', type2: '' },
  { index: '#0683', name: 'Aromatisse', type1: 'Fairy', type2: '' },
  { index: '#0684', name: 'Swirlix', type1: 'Fairy', type2: '' },
  { index: '#0685', name: 'Slurpuff', type1: 'Fairy', type2: '' },
  { index: '#0686', name: 'Inkay', type1: 'Dark', type2: 'Psychic' },
  { index: '#0687', name: 'Malamar', type1: 'Dark', type2: 'Psychic' },
  { index: '#0688', name: 'Binacle', type1: 'Rock', type2: 'Water' },
  { index: '#0689', name: 'Barbaracle', type1: 'Rock', type2: 'Water' },
  { index: '#0690', name: 'Skrelp', type1: 'Poison', type2: 'Water' },
  { index: '#0691', name: 'Dragalge', type1: 'Poison', type2: 'Dragon' },
  { index: '#0692', name: 'Clauncher', type1: 'Water', type2: '' },
  { index: '#0693', name: 'Clawitzer', type1: 'Water', type2: '' },
  { index: '#0694', name: 'Helioptile', type1: 'Electric', type2: 'Normal' },
  { index: '#0695', name: 'Heliolisk', type1: 'Electric', type2: 'Normal' },
  { index: '#0696', name: 'Tyrunt', type1: 'Rock', type2: 'Dragon' },
  { index: '#0697', name: 'Tyrantrum', type1: 'Rock', type2: 'Dragon' },
  { index: '#0698', name: 'Amaura', type1: 'Rock', type2: 'Ice' },
  { index: '#0699', name: 'Aurorus', type1: 'Rock', type2: 'Ice' },
  { index: '#0700', name: 'Sylveon', type1: 'Fairy', type2: '' },
  { index: '#0701', name: 'Hawlucha', type1: 'Fighting', type2: 'Flying' },
  { index: '#0702', name: 'Dedenne', type1: 'Electric', type2: 'Fairy' },
  { index: '#0703', name: 'Carbink', type1: 'Rock', type2: 'Fairy' },
  { index: '#0704', name: 'Goomy', type1: 'Dragon', type2: '' },
  { index: '#0705', name: 'Sliggoo', type1: 'Dragon', type2: '' },
  { index: '#0705', name: 'Hisuian Sliggoo', type1: 'Steel', type2: 'Dragon' },
  { index: '#0706', name: 'Goodra', type1: 'Dragon', type2: '' },
  { index: '#0706', name: 'Hisuian Goodra', type1: 'Steel', type2: 'Dragon' },
  { index: '#0707', name: 'Klefki', type1: 'Steel', type2: 'Fairy' },
  { index: '#0708', name: 'Phantump', type1: 'Ghost', type2: 'Grass' },
  { index: '#0709', name: 'Trevenant', type1: 'Ghost', type2: 'Grass' },
  { index: '#0710', name: 'Pumpkaboo', type1: 'Ghost', type2: 'Grass' },
  { index: '#0711', name: 'Gourgeist', type1: 'Ghost', type2: 'Grass' },
  { index: '#0712', name: 'Bergmite', type1: 'Ice', type2: '' },
  { index: '#0713', name: 'Avalugg', type1: 'Ice', type2: '' },
  { index: '#0713', name: 'Hisuian Avalugg', type1: 'Ice', type2: 'Rock' },
  { index: '#0714', name: 'Noibat', type1: 'Flying', type2: 'Dragon' },
  { index: '#0715', name: 'Noivern', type1: 'Flying', type2: 'Dragon' },
  { index: '#0716', name: 'Xerneas Neutral Mode', type1: 'Fairy', type2: '' },
  { index: '#0716', name: 'Xerneas Active Mode', type1: 'Fairy', type2: '' },
  { index: '#0717', name: 'Yveltal', type1: 'Dark', type2: 'Flying' },
  { index: '#0718', name: 'Zygarde 50% Forme', type1: 'Dragon', type2: 'Ground' },
  { index: '#0718', name: 'Zygarde 10% Forme', type1: 'Dragon', type2: 'Ground' },
  { index: '#0718', name: 'Zygarde Complete Forme', type1: 'Dragon', type2: 'Ground' },
  { index: '#0719', name: 'Diancie', type1: 'Rock', type2: 'Fairy' },
  { index: '#0720', name: 'Hoopa Hoopa Confined', type1: 'Psychic', type2: 'Ghost' },
  { index: '#0720', name: 'Hoopa Hoopa Unbound', type1: 'Psychic', type2: 'Dark' },
  { index: '#0721', name: 'Volcanion', type1: 'Fire', type2: 'Water' },
  { index: '#0722', name: 'Rowlet', type1: 'Grass', type2: 'Flying' },
  { index: '#0723', name: 'Dartrix', type1: 'Grass', type2: 'Flying' },
  { index: '#0724', name: 'Decidueye', type1: 'Grass', type2: 'Ghost' },
  { index: '#0724', name: 'Hisuian Decidueye', type1: 'Grass', type2: 'Fighting' },
  { index: '#0725', name: 'Litten', type1: 'Fire', type2: '' },
  { index: '#0726', name: 'Torracat', type1: 'Fire', type2: '' },
  { index: '#0727', name: 'Incineroar', type1: 'Fire', type2: 'Dark' },
  { index: '#0728', name: 'Popplio', type1: 'Water', type2: '' },
  { index: '#0729', name: 'Brionne', type1: 'Water', type2: '' },
  { index: '#0730', name: 'Primarina', type1: 'Water', type2: 'Fairy' },
  { index: '#0731', name: 'Pikipek', type1: 'Normal', type2: 'Flying' },
  { index: '#0732', name: 'Trumbeak', type1: 'Normal', type2: 'Flying' },
  { index: '#0733', name: 'Toucannon', type1: 'Normal', type2: 'Flying' },
  { index: '#0734', name: 'Yungoos', type1: 'Normal', type2: '' },
  { index: '#0735', name: 'Gumshoos', type1: 'Normal', type2: '' },
  { index: '#0736', name: 'Grubbin', type1: 'Bug', type2: '' },
  { index: '#0737', name: 'Charjabug', type1: 'Bug', type2: 'Electric' },
  { index: '#0738', name: 'Vikavolt', type1: 'Bug', type2: 'Electric' },
  { index: '#0739', name: 'Crabrawler', type1: 'Fighting', type2: '' },
  { index: '#0740', name: 'Crabominable', type1: 'Fighting', type2: 'Ice' },
  { index: '#0741', name: 'Oricorio Baile Style', type1: 'Fire', type2: 'Flying' },
  { index: '#0741', name: 'Oricorio Pom-Pom Style', type1: 'Electric', type2: 'Flying' },
  { index: '#0741', name: 'Oricorio Pa’u Style', type1: 'Psychic', type2: 'Flying' },
  { index: '#0741', name: 'Oricorio Sensu Style', type1: 'Ghost', type2: 'Flying' },
  { index: '#0742', name: 'Cutiefly', type1: 'Bug', type2: 'Fairy' },
  { index: '#0743', name: 'Ribombee', type1: 'Bug', type2: 'Fairy' },
  { index: '#0744', name: 'Rockruff', type1: 'Rock', type2: '' },
  { index: '#0745', name: 'Midday Lycanroc', type1: 'Rock', type2: '' },
  { index: '#0745', name: 'Midnight Lycanroc', type1: 'Rock', type2: '' },
  { index: '#0745', name: 'Dusk Lycanroc', type1: 'Rock', type2: '' },
  { index: '#0746', name: 'Solo Wishiwashi', type1: 'Water', type2: '' },
  { index: '#0746', name: 'School Wishiwashi', type1: 'Water', type2: '' },
  { index: '#0747', name: 'Mareanie', type1: 'Poison', type2: 'Water' },
  { index: '#0748', name: 'Toxapex', type1: 'Poison', type2: 'Water' },
  { index: '#0749', name: 'Mudbray', type1: 'Ground', type2: '' },
  { index: '#0750', name: 'Mudsdale', type1: 'Ground', type2: '' },
  { index: '#0751', name: 'Dewpider', type1: 'Water', type2: 'Bug' },
  { index: '#0752', name: 'Araquanid', type1: 'Water', type2: 'Bug' },
  { index: '#0753', name: 'Fomantis', type1: 'Grass', type2: '' },
  { index: '#0754', name: 'Lurantis', type1: 'Grass', type2: '' },
  { index: '#0755', name: 'Morelull', type1: 'Grass', type2: 'Fairy' },
  { index: '#0756', name: 'Shiinotic', type1: 'Grass', type2: 'Fairy' },
  { index: '#0757', name: 'Salandit', type1: 'Poison', type2: 'Fire' },
  { index: '#0758', name: 'Salazzle', type1: 'Poison', type2: 'Fire' },
  { index: '#0759', name: 'Stufful', type1: 'Normal', type2: 'Fighting' },
  { index: '#0760', name: 'Bewear', type1: 'Normal', type2: 'Fighting' },
  { index: '#0761', name: 'Bounsweet', type1: 'Grass', type2: '' },
  { index: '#0762', name: 'Steenee', type1: 'Grass', type2: '' },
  { index: '#0763', name: 'Tsareena', type1: 'Grass', type2: '' },
  { index: '#0764', name: 'Comfey', type1: 'Fairy', type2: '' },
  { index: '#0765', name: 'Oranguru', type1: 'Normal', type2: 'Psychic' },
  { index: '#0766', name: 'Passimian', type1: 'Fighting', type2: '' },
  { index: '#0767', name: 'Wimpod', type1: 'Bug', type2: 'Water' },
  { index: '#0768', name: 'Golisopod', type1: 'Bug', type2: 'Water' },
  { index: '#0769', name: 'Sandygast', type1: 'Ghost', type2: 'Ground' },
  { index: '#0770', name: 'Palossand', type1: 'Ghost', type2: 'Ground' },
  { index: '#0771', name: 'Pyukumuku', type1: 'Water', type2: '' },
  { index: '#0772', name: 'Type: Null', type1: 'Normal', type2: '' },
  { index: '#0773', name: 'Silvally Type: Normal', type1: 'Normal', type2: '' },
  { index: '#0774', name: 'Meteor Minior', type1: 'Rock', type2: 'Flying' },
  { index: '#0774', name: 'Minior Red Core', type1: 'Rock', type2: 'Flying' },
  { index: '#0775', name: 'Komala', type1: 'Normal', type2: '' },
  { index: '#0776', name: 'Turtonator', type1: 'Fire', type2: 'Dragon' },
  { index: '#0777', name: 'Togedemaru', type1: 'Electric', type2: 'Steel' },
  { index: '#0778', name: 'Disguised Mimikyu', type1: 'Ghost', type2: 'Fairy' },
  { index: '#0778', name: 'Busted Mimikyu', type1: 'Ghost', type2: 'Fairy' },
  { index: '#0779', name: 'Bruxish', type1: 'Water', type2: 'Psychic' },
  { index: '#0780', name: 'Drampa', type1: 'Normal', type2: 'Dragon' },
  { index: '#0781', name: 'Dhelmise', type1: 'Ghost', type2: 'Grass' },
  { index: '#0782', name: 'Jangmo-o', type1: 'Dragon', type2: '' },
  { index: '#0783', name: 'Hakamo-o', type1: 'Dragon', type2: 'Fighting' },
  { index: '#0784', name: 'Kommo-o', type1: 'Dragon', type2: 'Fighting' },
  { index: '#0785', name: 'Tapu Koko', type1: 'Electric', type2: 'Fairy' },
  { index: '#0786', name: 'Tapu Lele', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0787', name: 'Tapu Bulu', type1: 'Grass', type2: 'Fairy' },
  { index: '#0788', name: 'Tapu Fini', type1: 'Water', type2: 'Fairy' },
  { index: '#0789', name: 'Cosmog', type1: 'Psychic', type2: '' },
  { index: '#0790', name: 'Cosmoem', type1: 'Psychic', type2: '' },
  { index: '#0791', name: 'Solgaleo', type1: 'Psychic', type2: 'Steel' },
  { index: '#0792', name: 'Lunala', type1: 'Psychic', type2: 'Ghost' },
  { index: '#0793', name: 'Nihilego', type1: 'Rock', type2: 'Poison' },
  { index: '#0794', name: 'Buzzwole', type1: 'Bug', type2: 'Fighting' },
  { index: '#0795', name: 'Pheromosa', type1: 'Bug', type2: 'Fighting' },
  { index: '#0796', name: 'Xurkitree', type1: 'Electric', type2: '' },
  { index: '#0797', name: 'Celesteela', type1: 'Steel', type2: 'Flying' },
  { index: '#0798', name: 'Kartana', type1: 'Grass', type2: 'Steel' },
  { index: '#0799', name: 'Guzzlord', type1: 'Dark', type2: 'Dragon' },
  { index: '#0800', name: 'Necrozma', type1: 'Psychic', type2: '' },
  { index: '#0800', name: 'Necrozma Dusk Mane', type1: 'Psychic', type2: 'Steel' },
  { index: '#0800', name: 'Necrozma Dawn Wings', type1: 'Psychic', type2: 'Ghost' },
  { index: '#0801', name: 'Magearna', type1: 'Steel', type2: 'Fairy' },
  { index: '#0802', name: 'Marshadow', type1: 'Fighting', type2: 'Ghost' },
  { index: '#0803', name: 'Poipole', type1: 'Poison', type2: '' },
  { index: '#0804', name: 'Naganadel', type1: 'Poison', type2: 'Dragon' },
  { index: '#0805', name: 'Stakataka', type1: 'Rock', type2: 'Steel' },
  { index: '#0806', name: 'Blacephalon', type1: 'Fire', type2: 'Ghost' },
  { index: '#0807', name: 'Zeraora', type1: 'Electric', type2: '' },
  { index: '#0808', name: 'Meltan', type1: 'Steel', type2: '' },
  { index: '#0809', name: 'Melmetal', type1: 'Steel', type2: '' },
  { index: '#0810', name: 'Grookey', type1: 'Grass', type2: '' },
  { index: '#0811', name: 'Thwackey', type1: 'Grass', type2: '' },
  { index: '#0812', name: 'Rillaboom', type1: 'Grass', type2: '' },
  { index: '#0813', name: 'Scorbunny', type1: 'Fire', type2: '' },
  { index: '#0814', name: 'Raboot', type1: 'Fire', type2: '' },
  { index: '#0815', name: 'Cinderace', type1: 'Fire', type2: '' },
  { index: '#0816', name: 'Sobble', type1: 'Water', type2: '' },
  { index: '#0817', name: 'Drizzile', type1: 'Water', type2: '' },
  { index: '#0818', name: 'Inteleon', type1: 'Water', type2: '' },
  { index: '#0819', name: 'Skwovet', type1: 'Normal', type2: '' },
  { index: '#0820', name: 'Greedent', type1: 'Normal', type2: '' },
  { index: '#0821', name: 'Rookidee', type1: 'Flying', type2: '' },
  { index: '#0822', name: 'Corvisquire', type1: 'Flying', type2: '' },
  { index: '#0823', name: 'Corviknight', type1: 'Flying', type2: 'Steel' },
  { index: '#0824', name: 'Blipbug', type1: 'Bug', type2: '' },
  { index: '#0825', name: 'Dottler', type1: 'Bug', type2: 'Psychic' },
  { index: '#0826', name: 'Orbeetle', type1: 'Bug', type2: 'Psychic' },
  { index: '#0827', name: 'Nickit', type1: 'Dark', type2: '' },
  { index: '#0828', name: 'Thievul', type1: 'Dark', type2: '' },
  { index: '#0829', name: 'Gossifleur', type1: 'Grass', type2: '' },
  { index: '#0830', name: 'Eldegoss', type1: 'Grass', type2: '' },
  { index: '#0831', name: 'Wooloo', type1: 'Normal', type2: '' },
  { index: '#0832', name: 'Dubwool', type1: 'Normal', type2: '' },
  { index: '#0833', name: 'Chewtle', type1: 'Water', type2: '' },
  { index: '#0834', name: 'Drednaw', type1: 'Water', type2: 'Rock' },
  { index: '#0835', name: 'Yamper', type1: 'Electric', type2: '' },
  { index: '#0836', name: 'Boltund', type1: 'Electric', type2: '' },
  { index: '#0837', name: 'Rolycoly', type1: 'Rock', type2: '' },
  { index: '#0838', name: 'Carkol', type1: 'Rock', type2: 'Fire' },
  { index: '#0839', name: 'Coalossal', type1: 'Rock', type2: 'Fire' },
  { index: '#0840', name: 'Applin', type1: 'Grass', type2: 'Dragon' },
  { index: '#0841', name: 'Flapple', type1: 'Grass', type2: 'Dragon' },
  { index: '#0842', name: 'Appletun', type1: 'Grass', type2: 'Dragon' },
  { index: '#0843', name: 'Silicobra', type1: 'Ground', type2: '' },
  { index: '#0844', name: 'Sandaconda', type1: 'Ground', type2: '' },
  { index: '#0845', name: 'Cramorant', type1: 'Flying', type2: 'Water' },
  { index: '#0845', name: 'Cramorant Gulping Form', type1: 'Flying', type2: 'Water' },
  { index: '#0845', name: 'Cramorant Gorging Form', type1: 'Flying', type2: 'Water' },
  { index: '#0846', name: 'Arrokuda', type1: 'Water', type2: '' },
  { index: '#0847', name: 'Barraskewda', type1: 'Water', type2: '' },
  { index: '#0848', name: 'Toxel', type1: 'Electric', type2: 'Poison' },
  { index: '#0849', name: 'Toxtricity Amped Form', type1: 'Electric', type2: 'Poison' },
  { index: '#0849', name: 'Toxtricity Low Key Form', type1: 'Electric', type2: 'Poison' },
  { index: '#0850', name: 'Sizzlipede', type1: 'Fire', type2: 'Bug' },
  { index: '#0851', name: 'Centiskorch', type1: 'Fire', type2: 'Bug' },
  { index: '#0852', name: 'Clobbopus', type1: 'Fighting', type2: '' },
  { index: '#0853', name: 'Grapploct', type1: 'Fighting', type2: '' },
  { index: '#0854', name: 'Sinistea', type1: 'Ghost', type2: '' },
  { index: '#0855', name: 'Polteageist', type1: 'Ghost', type2: '' },
  { index: '#0856', name: 'Hatenna', type1: 'Psychic', type2: '' },
  { index: '#0857', name: 'Hattrem', type1: 'Psychic', type2: '' },
  { index: '#0858', name: 'Hatterene', type1: 'Psychic', type2: 'Fairy' },
  { index: '#0859', name: 'Impidimp', type1: 'Dark', type2: 'Fairy' },
  { index: '#0860', name: 'Morgrem', type1: 'Dark', type2: 'Fairy' },
  { index: '#0861', name: 'Grimmsnarl', type1: 'Dark', type2: 'Fairy' },
  { index: '#0862', name: 'Obstagoon', type1: 'Dark', type2: 'Normal' },
  { index: '#0863', name: 'Perrserker', type1: 'Steel', type2: '' },
  { index: '#0864', name: 'Cursola', type1: 'Ghost', type2: '' },
  { index: '#0865', name: 'Sirfetch\'d', type1: 'Fighting', type2: '' },
  { index: '#0866', name: 'Mr. Rime', type1: 'Ice', type2: 'Psychic' },
  { index: '#0867', name: 'Runerigus', type1: 'Ground', type2: 'Ghost' },
  { index: '#0868', name: 'Milcery', type1: 'Fairy', type2: '' },
  { index: '#0869', name: 'Alcremie Vanilla Cream', type1: 'Fairy', type2: '' },
  { index: '#0870', name: 'Falinks', type1: 'Fighting', type2: '' },
  { index: '#0871', name: 'Pincurchin', type1: 'Electric', type2: '' },
  { index: '#0872', name: 'Snom', type1: 'Ice', type2: 'Bug' },
  { index: '#0873', name: 'Frosmoth', type1: 'Ice', type2: 'Bug' },
  { index: '#0874', name: 'Stonjourner', type1: 'Rock', type2: '' },
  { index: '#0875', name: 'Eiscue Ice Face', type1: 'Ice', type2: '' },
  { index: '#0875', name: 'Eiscue Noice Face', type1: 'Ice', type2: '' },
  { index: '#0876', name: 'Indeedee Male', type1: 'Psychic', type2: 'Normal' },
  { index: '#0876', name: 'Indeedee Female', type1: 'Psychic', type2: 'Normal' },
  { index: '#0877', name: 'Morpeko Full Belly Mode', type1: 'Electric', type2: 'Dark' },
  { index: '#0877', name: 'Morpeko Hangry Mode', type1: 'Electric', type2: 'Dark' },
  { index: '#0878', name: 'Cufant', type1: 'Steel', type2: '' },
  { index: '#0879', name: 'Copperajah', type1: 'Steel', type2: '' },
  { index: '#0880', name: 'Dracozolt', type1: 'Electric', type2: 'Dragon' },
  { index: '#0881', name: 'Arctozolt', type1: 'Electric', type2: 'Ice' },
  { index: '#0882', name: 'Dracovish', type1: 'Water', type2: 'Dragon' },
  { index: '#0883', name: 'Arctovish', type1: 'Water', type2: 'Ice' },
  { index: '#0884', name: 'Duraludon', type1: 'Steel', type2: 'Dragon' },
  { index: '#0885', name: 'Dreepy', type1: 'Dragon', type2: 'Ghost' },
  { index: '#0886', name: 'Drakloak', type1: 'Dragon', type2: 'Ghost' },
  { index: '#0887', name: 'Dragapult', type1: 'Dragon', type2: 'Ghost' },
  { index: '#0888', name: 'Zacian Hero of Many Battles', type1: 'Fairy', type2: '' },
  { index: '#0888', name: 'Zacian Crowned Sword', type1: 'Fairy', type2: 'Steel' },
  { index: '#0889', name: 'Zamazenta Hero of Many Battles', type1: 'Fighting', type2: '' },
  { index: '#0889', name: 'Zamazenta Crowned Shield', type1: 'Fighting', type2: 'Steel' },
  { index: '#0890', name: 'Eternatus', type1: 'Poison', type2: 'Dragon' },
  { index: '#0891', name: 'Kubfu', type1: 'Fighting', type2: '' },
  { index: '#0892', name: 'Urshifu Single Strike Style', type1: 'Fighting', type2: 'Dark' },
  { index: '#0892', name: 'Urshifu Rapid Strike Style', type1: 'Fighting', type2: 'Water' },
  { index: '#0893', name: 'Zarude', type1: 'Dark', type2: 'Grass' },
  { index: '#0894', name: 'Regieleki', type1: 'Electric', type2: '' },
  { index: '#0895', name: 'Regidrago', type1: 'Dragon', type2: '' },
  { index: '#0896', name: 'Glastrier', type1: 'Ice', type2: '' },
  { index: '#0897', name: 'Spectrier', type1: 'Ghost', type2: '' },
  { index: '#0898', name: 'Calyrex', type1: 'Psychic', type2: 'Grass' },
  { index: '#0898', name: 'Calyrex Ice Rider', type1: 'Psychic', type2: 'Ice' },
  { index: '#0898', name: 'Calyrex Shadow Rider', type1: 'Psychic', type2: 'Ghost' },
  { index: '#0899', name: 'Wyrdeer', type1: 'Normal', type2: 'Psychic' },
  { index: '#0900', name: 'Kleavor', type1: 'Bug', type2: 'Rock' },
  { index: '#0901', name: 'Ursaluna', type1: 'Ground', type2: 'Normal' },
  { index: '#0901', name: 'Ursaluna Bloodmoon', type1: 'Ground', type2: 'Normal' },
  { index: '#0902', name: 'Basculegion Male', type1: 'Water', type2: 'Ghost' },
  { index: '#0902', name: 'Basculegion Female', type1: 'Water', type2: 'Ghost' },
  { index: '#0903', name: 'Sneasler', type1: 'Fighting', type2: 'Poison' },
  { index: '#0904', name: 'Overqwil', type1: 'Dark', type2: 'Poison' },
  { index: '#0905', name: 'Enamorus Incarnate Forme', type1: 'Fairy', type2: 'Flying' },
  { index: '#0905', name: 'Enamorus Therian Forme', type1: 'Fairy', type2: 'Flying' },
  { index: '#0906', name: 'Sprigatito', type1: 'Grass', type2: '' },
  { index: '#0907', name: 'Floragato', type1: 'Grass', type2: '' },
  { index: '#0908', name: 'Meowscarada', type1: 'Grass', type2: 'Dark' },
  { index: '#0909', name: 'Fuecoco', type1: 'Fire', type2: '' },
  { index: '#0910', name: 'Crocalor', type1: 'Fire', type2: '' },
  { index: '#0911', name: 'Skeledirge', type1: 'Fire', type2: 'Ghost' },
  { index: '#0912', name: 'Quaxly', type1: 'Water', type2: '' },
  { index: '#0913', name: 'Quaxwell', type1: 'Water', type2: '' },
  { index: '#0914', name: 'Quaquaval', type1: 'Water', type2: 'Fighting' },
  { index: '#0915', name: 'Lechonk', type1: 'Normal', type2: '' },
  { index: '#0916', name: 'Oinkologne Male', type1: 'Normal', type2: '' },
  { index: '#0916', name: 'Oinkologne Female', type1: 'Normal', type2: '' },
  { index: '#0917', name: 'Tarountula', type1: 'Bug', type2: '' },
  { index: '#0918', name: 'Spidops', type1: 'Bug', type2: '' },
  { index: '#0919', name: 'Nymble', type1: 'Bug', type2: '' },
  { index: '#0920', name: 'Lokix', type1: 'Bug', type2: 'Dark' },
  { index: '#0921', name: 'Pawmi', type1: 'Electric', type2: '' },
  { index: '#0922', name: 'Pawmo', type1: 'Electric', type2: 'Fighting' },
  { index: '#0923', name: 'Pawmot', type1: 'Electric', type2: 'Fighting' },
  { index: '#0924', name: 'Tandemaus', type1: 'Normal', type2: '' },
  { index: '#0925', name: 'Maushold Family of Three', type1: 'Normal', type2: '' },
  { index: '#0925', name: 'Maushold Family of Four', type1: 'Normal', type2: '' },
  { index: '#0926', name: 'Fidough', type1: 'Fairy', type2: '' },
  { index: '#0927', name: 'Dachsbun', type1: 'Fairy', type2: '' },
  { index: '#0928', name: 'Smoliv', type1: 'Grass', type2: 'Normal' },
  { index: '#0929', name: 'Dolliv', type1: 'Grass', type2: 'Normal' },
  { index: '#0930', name: 'Arboliva', type1: 'Grass', type2: 'Normal' },
  { index: '#0931', name: 'Squawkabilly Green Plumage', type1: 'Normal', type2: 'Flying' },
  { index: '#0931', name: 'Squawkabilly Blue Plumage', type1: 'Normal', type2: 'Flying' },
  { index: '#0931', name: 'Squawkabilly Yellow Plumage', type1: 'Normal', type2: 'Flying' },
  { index: '#0931', name: 'Squawkabilly White Plumage', type1: 'Normal', type2: 'Flying' },
  { index: '#0932', name: 'Nacli', type1: 'Rock', type2: '' },
  { index: '#0933', name: 'Naclstack', type1: 'Rock', type2: '' },
  { index: '#0934', name: 'Garganacl', type1: 'Rock', type2: '' },
  { index: '#0935', name: 'Charcadet', type1: 'Fire', type2: '' },
  { index: '#0936', name: 'Armarouge', type1: 'Fire', type2: 'Psychic' },
  { index: '#0937', name: 'Ceruledge', type1: 'Fire', type2: 'Ghost' },
  { index: '#0938', name: 'Tadbulb', type1: 'Electric', type2: '' },
  { index: '#0939', name: 'Bellibolt', type1: 'Electric', type2: '' },
  { index: '#0940', name: 'Wattrel', type1: 'Electric', type2: 'Flying' },
  { index: '#0941', name: 'Kilowattrel', type1: 'Electric', type2: 'Flying' },
  { index: '#0942', name: 'Maschiff', type1: 'Dark', type2: '' },
  { index: '#0943', name: 'Mabosstiff', type1: 'Dark', type2: '' },
  { index: '#0944', name: 'Shroodle', type1: 'Poison', type2: 'Normal' },
  { index: '#0945', name: 'Grafaiai', type1: 'Poison', type2: 'Normal' },
  { index: '#0946', name: 'Bramblin', type1: 'Grass', type2: 'Ghost' },
  { index: '#0947', name: 'Brambleghast', type1: 'Grass', type2: 'Ghost' },
  { index: '#0948', name: 'Toedscool', type1: 'Ground', type2: 'Grass' },
  { index: '#0949', name: 'Toedscruel', type1: 'Ground', type2: 'Grass' },
  { index: '#0950', name: 'Klawf', type1: 'Rock', type2: '' },
  { index: '#0951', name: 'Capsakid', type1: 'Grass', type2: '' },
  { index: '#0952', name: 'Scovillain', type1: 'Grass', type2: 'Fire' },
  { index: '#0953', name: 'Rellor', type1: 'Bug', type2: '' },
  { index: '#0954', name: 'Rabsca', type1: 'Bug', type2: 'Psychic' },
  { index: '#0955', name: 'Flittle', type1: 'Psychic', type2: '' },
  { index: '#0956', name: 'Espathra', type1: 'Psychic', type2: '' },
  { index: '#0957', name: 'Tinkatink', type1: 'Fairy', type2: 'Steel' },
  { index: '#0958', name: 'Tinkatuff', type1: 'Fairy', type2: 'Steel' },
  { index: '#0959', name: 'Tinkaton', type1: 'Fairy', type2: 'Steel' },
  { index: '#0960', name: 'Wiglett', type1: 'Water', type2: '' },
  { index: '#0961', name: 'Wugtrio', type1: 'Water', type2: '' },
  { index: '#0962', name: 'Bombirdier', type1: 'Flying', type2: 'Dark' },
  { index: '#0963', name: 'Finizen', type1: 'Water', type2: '' },
  { index: '#0964', name: 'Palafin Zero Form', type1: 'Water', type2: '' },
  { index: '#0964', name: 'Palafin Hero Form', type1: 'Water', type2: '' },
  { index: '#0965', name: 'Varoom', type1: 'Steel', type2: 'Poison' },
  { index: '#0966', name: 'Revavroom', type1: 'Steel', type2: 'Poison' },
  { index: '#0967', name: 'Cyclizar', type1: 'Dragon', type2: 'Normal' },
  { index: '#0968', name: 'Orthworm', type1: 'Steel', type2: '' },
  { index: '#0969', name: 'Glimmet', type1: 'Rock', type2: 'Poison' },
  { index: '#0970', name: 'Glimmora', type1: 'Rock', type2: 'Poison' },
  { index: '#0971', name: 'Greavard', type1: 'Ghost', type2: '' },
  { index: '#0972', name: 'Houndstone', type1: 'Ghost', type2: '' },
  { index: '#0973', name: 'Flamigo', type1: 'Flying', type2: 'Fighting' },
  { index: '#0974', name: 'Cetoddle', type1: 'Ice', type2: '' },
  { index: '#0975', name: 'Cetitan', type1: 'Ice', type2: '' },
  { index: '#0976', name: 'Veluza', type1: 'Water', type2: 'Psychic' },
  { index: '#0977', name: 'Dondozo', type1: 'Water', type2: '' },
  { index: '#0978', name: 'Tatsugiri Curly Form', type1: 'Dragon', type2: 'Water' },
  { index: '#0978', name: 'Tatsugiri Droopy Form', type1: 'Dragon', type2: 'Water' },
  { index: '#0978', name: 'Tatsugiri Stretchy Form', type1: 'Dragon', type2: 'Water' },
  { index: '#0979', name: 'Annihilape', type1: 'Fighting', type2: 'Ghost' },
  { index: '#0980', name: 'Clodsire', type1: 'Poison', type2: 'Ground' },
  { index: '#0981', name: 'Farigiraf', type1: 'Normal', type2: 'Psychic' },
  { index: '#0982', name: 'Dudunsparce Two-Segment Form', type1: 'Normal', type2: '' },
  { index: '#0982', name: 'Dudunsparce Three-Segment Form', type1: 'Normal', type2: '' },
  { index: '#0983', name: 'Kingambit', type1: 'Dark', type2: 'Steel' },
  { index: '#0984', name: 'Great Tusk', type1: 'Ground', type2: 'Fighting' },
  { index: '#0985', name: 'Scream Tail', type1: 'Fairy', type2: 'Psychic' },
  { index: '#0986', name: 'Brute Bonnet', type1: 'Grass', type2: 'Dark' },
  { index: '#0987', name: 'Flutter Mane', type1: 'Ghost', type2: 'Fairy' },
  { index: '#0988', name: 'Slither Wing', type1: 'Bug', type2: 'Fighting' },
  { index: '#0989', name: 'Sandy Shocks', type1: 'Electric', type2: 'Ground' },
  { index: '#0990', name: 'Iron Treads', type1: 'Ground', type2: 'Steel' },
  { index: '#0991', name: 'Iron Bundle', type1: 'Ice', type2: 'Water' },
  { index: '#0992', name: 'Iron Hands', type1: 'Fighting', type2: 'Electric' },
  { index: '#0993', name: 'Iron Jugulis', type1: 'Dark', type2: 'Flying' },
  { index: '#0994', name: 'Iron Moth', type1: 'Fire', type2: 'Poison' },
  { index: '#0995', name: 'Iron Thorns', type1: 'Rock', type2: 'Electric' },
  { index: '#0996', name: 'Frigibax', type1: 'Dragon', type2: 'Ice' },
  { index: '#0997', name: 'Arctibax', type1: 'Dragon', type2: 'Ice' },
  { index: '#0998', name: 'Baxcalibur', type1: 'Dragon', type2: 'Ice' },
  { index: '#0999', name: 'Gimmighoul Chest Form', type1: 'Ghost', type2: '' },
  { index: '#0999', name: 'Gimmighoul Roaming Form', type1: 'Ghost', type2: '' },
  { index: '#1000', name: 'Gholdengo', type1: 'Steel', type2: 'Ghost' },
  { index: '#1001', name: 'Wo-Chien', type1: 'Dark', type2: 'Grass' },
  { index: '#1002', name: 'Chien-Pao', type1: 'Dark', type2: 'Ice' },
  { index: '#1003', name: 'Ting-Lu', type1: 'Dark', type2: 'Ground' },
  { index: '#1004', name: 'Chi-Yu', type1: 'Dark', type2: 'Fire' },
  { index: '#1005', name: 'Roaring Moon', type1: 'Dragon', type2: 'Dark' },
  { index: '#1006', name: 'Iron Valiant', type1: 'Fairy', type2: 'Fighting' },
  { index: '#1007', name: 'Koraidon Apex Build', type1: 'Fighting', type2: 'Dragon' },
  { index: '#1008', name: 'Miraidon Ultimate Mode', type1: 'Electric', type2: 'Dragon' },
  { index: '#1009', name: 'Walking Wake', type1: 'Water', type2: 'Dragon' },
  { index: '#1010', name: 'Iron Leaves', type1: 'Grass', type2: 'Psychic' },
  { index: '#1011', name: 'Dipplin', type1: 'Grass', type2: 'Dragon' },
  { index: '#1012', name: 'Poltchageist', type1: 'Grass', type2: 'Ghost' },
  { index: '#1013', name: 'Sinistcha', type1: 'Grass', type2: 'Ghost' },
  { index: '#1014', name: 'Okidogi', type1: 'Poison', type2: 'Fighting' },
  { index: '#1015', name: 'Munkidori', type1: 'Poison', type2: 'Psychic' },
  { index: '#1016', name: 'Fezandipiti', type1: 'Poison', type2: 'Fairy' },
  { index: '#1017', name: 'Ogerpon Teal Mask', type1: 'Grass', type2: '' },
  { index: '#1017', name: 'Ogerpon Wellspring Mask', type1: 'Grass', type2: 'Water' },
  { index: '#1017', name: 'Ogerpon Hearthflame Mask', type1: 'Grass', type2: 'Fire' },
  { index: '#1017', name: 'Ogerpon Cornerstone Mask', type1: 'Grass', type2: 'Rock' },
  { index: '#1018', name: 'Archaludon', type1: 'Steel', type2: 'Dragon' },
  { index: '#1019', name: 'Hydrapple', type1: 'Grass', type2: 'Dragon' },
  { index: '#1020', name: 'Gouging Fire', type1: 'Fire', type2: 'Dragon' },
  { index: '#1021', name: 'Raging Bolt', type1: 'Electric', type2: 'Dragon' },
  { index: '#1022', name: 'Iron Boulder', type1: 'Rock', type2: 'Psychic' },
  { index: '#1023', name: 'Iron Crown', type1: 'Steel', type2: 'Psychic' },
  { index: '#1024', name: 'Terapagos Normal Form', type1: 'Normal', type2: '' },
  { index: '#1024', name: 'Terapagos Terastal Form', type1: 'Normal', type2: '' },
  { index: '#1025', name: 'Pecharunt', type1: 'Poison', type2: 'Ghost' },
];
